/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol AEBookMetadataProvider <NSObject>
@required
-(BOOL)isManagedWithAssetID:(id)arg1;
-(id)assetURLForAssetID:(id)arg1;
-(id)pathToContextDirectoryForAssetID:(id)arg1;
-(id)bookVersionStringForAssetID:(id)arg1;

@end

