/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <IMCommonCore/BKSeriesDataItem.h>

@class NSString, NSNumber, NSArray, NSDictionary;

@interface AEUserPublishingProductProfile : NSObject <BKSeriesDataItem> {

	NSDictionary* _profileDictionary;

}

@property (nonatomic,readonly) NSString * seriesID; 
@property (nonatomic,readonly) NSArray * children; 
@property (nonatomic,readonly) NSArray * childrenIDs; 
@property (nonatomic,readonly) BOOL isSeries; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * series_adamId; 
@property (nonatomic,readonly) NSString * series_sortTitle; 
@property (nonatomic,readonly) NSString * series_title; 
@property (nonatomic,readonly) NSString * series_sortAuthor; 
@property (nonatomic,readonly) NSString * series_author; 
@property (nonatomic,readonly) NSNumber * series_isExplicit; 
@property (nonatomic,readonly) NSString * series_formattedPrice; 
@property (nonatomic,readonly) NSArray * series_genres; 
@property (nonatomic,readonly) NSString * series_genre; 
@property (nonatomic,readonly) BOOL isExplicit; 
@property (nonatomic,readonly) NSString * buyParameters; 
@property (nonatomic,readonly) BOOL isPreorder; 
@property (nonatomic,readonly) NSDictionary * profileDictionary;              //@synthesize profileDictionary=_profileDictionary - In the implementation block
@property (nonatomic,readonly) NSString * adamId; 
-(NSArray *)childrenIDs;
-(NSString *)seriesID;
-(BOOL)isSeries;
-(NSArray *)children;
-(NSArray *)series_genres;
-(id)series_seriesInfo;
-(unsigned long long)series_position;
-(NSString *)series_genre;
-(NSString *)series_adamId;
-(NSString *)series_sortTitle;
-(NSString *)series_sortAuthor;
-(NSString *)series_title;
-(NSString *)series_author;
-(NSNumber *)series_isExplicit;
-(id)series_seriesId;
-(id)series_seriesTitle;
-(id)series_displayLabel;
-(NSString *)series_formattedPrice;
-(NSDictionary *)profileDictionary;
-(BOOL)_isContentRatingExplicitForInfo:(id)arg1 ;
-(id)_offer;
-(id)urlForCoverImageOfSize:(CGSize)arg1 ;
-(NSString *)description;
-(id)objectForKey:(id)arg1 ;
-(NSString *)adamId;
-(NSString *)buyParameters;
-(id)initWithProfileDictionary:(id)arg1 ;
-(BOOL)isExplicit;
-(BOOL)isPreorder;
@end

