/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IMAnimationTracker : NSObject {

	unsigned long long _animationCount;
	/*^block*/id _completion;

}
+(id)animationTrackerWithCompletion:(/*^block*/id)arg1 ;
-(void)addAnimationWithBlock:(/*^block*/id)arg1 ;
-(id)initWithCompletion:(/*^block*/id)arg1 ;
@end

