/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IMDevice : NSObject
+(id)currentDevice;
-(unsigned long long)numberOfCPUCores;
-(void)currentMemoryStatistics:(unsigned long long*)arg1 rsize:(unsigned long long*)arg2 available:(unsigned long long*)arg3 total:(unsigned long long*)arg4 ;
-(BOOL)trackPadScrollDirectionIsNatural;
-(BOOL)hasNetwork;
-(BOOL)isInternalInstall;
@end

