/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSMutableDictionary;

@interface IMLibraryFragmentFilter : NSObject <NSSecureCoding> {

	NSMutableDictionary* _identifiedDocuments;
	SCD_Struct_IM4 _specification;

}
+(SCD_Struct_IM6)fragmentFilterSpecificationForDocumentLength:(long long)arg1 librarySpecification:(SCD_Struct_IM4)arg2 ;
+(BOOL)supportsSecureCoding;
-(void)addFilter:(id)arg1 withIdentifier:(id)arg2 ;
-(id)initWithFilterSpecification:(SCD_Struct_IM4)arg1 ;
-(void)addDocument:(id)arg1 withIdentifier:(id)arg2 ;
-(BOOL)containsDocumentWithIdentifier:(id)arg1 ;
-(id)allIdentifiers;
-(id)candidateIdentifiersForQuery:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(unsigned long long)documentCount;
@end

