/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMutableDictionary, NSCountedSet, NSMutableSet, NSObject;

@interface IMPersistentCacheManager : NSObject {

	NSMutableDictionary* _caches;
	NSCountedSet* _pathRequestCount;
	NSMutableSet* _excludedCachesForCleanup;
	NSObject*<OS_dispatch_queue> _accessQueue;

}
+(id)sharedInstance;
-(id)cacheForPath:(id)arg1 maxSize:(unsigned long long)arg2 ;
-(void)purgeFromCache:(id)arg1 ;
-(void)cleanUpCacheFilesInPath:(id)arg1 withExtension:(id)arg2 ;
-(void)_cleanCachesInPath:(id)arg1 ;
-(void)addCleanupExclusionPath:(id)arg1 ;
-(id)init;
@end

