/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:12 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSURL, NSString, NSObject, NSHashTable;

@interface IMUbiquityStatusMonitor : NSObject {

	BOOL _isUbiquityEnabled;
	BOOL _optedIn;
	NSURL* _containerURL;
	NSURL* _documentsURL;
	id _lastArchivedUbiquityIdentityToken;
	id _currentUbiquityIdentityToken;
	NSString* _containerIdentifier;
	NSObject*<OS_dispatch_queue> _serialQueue;
	NSHashTable* _observers;

}

@property (assign,nonatomic) BOOL isUbiquityEnabled;                                //@synthesize isUbiquityEnabled=_isUbiquityEnabled - In the implementation block
@property (nonatomic,copy,readonly) id ubiquityIdentityToken; 
@property (nonatomic,copy) NSURL * containerURL;                                    //@synthesize containerURL=_containerURL - In the implementation block
@property (nonatomic,copy) NSURL * documentsURL;                                    //@synthesize documentsURL=_documentsURL - In the implementation block
@property (nonatomic,copy) id lastArchivedUbiquityIdentityToken;                    //@synthesize lastArchivedUbiquityIdentityToken=_lastArchivedUbiquityIdentityToken - In the implementation block
@property (nonatomic,copy) id currentUbiquityIdentityToken;                         //@synthesize currentUbiquityIdentityToken=_currentUbiquityIdentityToken - In the implementation block
@property (nonatomic,copy) NSString * containerIdentifier;                          //@synthesize containerIdentifier=_containerIdentifier - In the implementation block
@property (assign,nonatomic) BOOL optedIn;                                          //@synthesize optedIn=_optedIn - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> serialQueue;              //@synthesize serialQueue=_serialQueue - In the implementation block
@property (nonatomic,retain) NSHashTable * observers;                               //@synthesize observers=_observers - In the implementation block
+(id)itunesuUbiquitousStatusMonitor;
-(void)sq_refreshUbiquityAvailabilityStatus;
-(void)p_ubiquityIdentityDidChange:(id)arg1 ;
-(BOOL)isUbiquityEnabled;
-(void)setOptedIn:(BOOL)arg1 ;
-(id)currentUbiquityIdentityToken;
-(id)lastArchivedUbiquityIdentityToken;
-(void)sq_archiveCurrentUbiquityIdentityToken;
-(void)updateWithOptedIn:(BOOL)arg1 ;
-(void)restartObserving;
-(void)setIsUbiquityEnabled:(BOOL)arg1 ;
-(void)setContainerURL:(NSURL *)arg1 ;
-(void)setDocumentsURL:(NSURL *)arg1 ;
-(void)setLastArchivedUbiquityIdentityToken:(id)arg1 ;
-(void)setCurrentUbiquityIdentityToken:(id)arg1 ;
-(NSURL *)containerURL;
-(void)setSerialQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(NSURL *)documentsURL;
-(BOOL)optedIn;
-(id)ubiquityIdentityToken;
-(void)setObservers:(NSHashTable *)arg1 ;
-(NSHashTable *)observers;
-(NSString *)containerIdentifier;
-(void)setContainerIdentifier:(NSString *)arg1 ;
-(NSObject*<OS_dispatch_queue>)serialQueue;
-(id)initWithContainerIdentifier:(id)arg1 ;
@end

