/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface NTPBEndpointConfig : PBCodable <NSCopying> {

	NSString* _clientApiBaseUrl;
	int _environment;
	NSString* _eventRelayBaseUrl;
	NSString* _eventRelayBatchBaseUrl;

}

@property (assign,nonatomic) int environment;                                //@synthesize environment=_environment - In the implementation block
@property (nonatomic,readonly) BOOL hasClientApiBaseUrl; 
@property (nonatomic,retain) NSString * clientApiBaseUrl;                    //@synthesize clientApiBaseUrl=_clientApiBaseUrl - In the implementation block
@property (nonatomic,readonly) BOOL hasEventRelayBaseUrl; 
@property (nonatomic,retain) NSString * eventRelayBaseUrl;                   //@synthesize eventRelayBaseUrl=_eventRelayBaseUrl - In the implementation block
@property (nonatomic,readonly) BOOL hasEventRelayBatchBaseUrl; 
@property (nonatomic,retain) NSString * eventRelayBatchBaseUrl;              //@synthesize eventRelayBatchBaseUrl=_eventRelayBatchBaseUrl - In the implementation block
-(void)setClientApiBaseUrl:(NSString *)arg1 ;
-(void)setEventRelayBaseUrl:(NSString *)arg1 ;
-(void)setEventRelayBatchBaseUrl:(NSString *)arg1 ;
-(BOOL)hasClientApiBaseUrl;
-(BOOL)hasEventRelayBaseUrl;
-(BOOL)hasEventRelayBatchBaseUrl;
-(NSString *)clientApiBaseUrl;
-(NSString *)eventRelayBaseUrl;
-(NSString *)eventRelayBatchBaseUrl;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(int)environment;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)setEnvironment:(int)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
@end

