/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface NTPBAdExposureOpportunity : PBCodable <NSCopying> {

	NSString* _adSlotId;
	int _durationInFeed;
	int _errorCode;
	int _responseTime;
	int _screenfulsFromTop;
	BOOL _isExpanded;
	BOOL _isFilled;
	SCD_Struct_NT3 _has;

}

@property (assign,nonatomic) BOOL hasIsExpanded; 
@property (assign,nonatomic) BOOL isExpanded;                        //@synthesize isExpanded=_isExpanded - In the implementation block
@property (assign,nonatomic) BOOL hasIsFilled; 
@property (assign,nonatomic) BOOL isFilled;                          //@synthesize isFilled=_isFilled - In the implementation block
@property (nonatomic,readonly) BOOL hasAdSlotId; 
@property (nonatomic,retain) NSString * adSlotId;                    //@synthesize adSlotId=_adSlotId - In the implementation block
@property (assign,nonatomic) BOOL hasDurationInFeed; 
@property (assign,nonatomic) int durationInFeed;                     //@synthesize durationInFeed=_durationInFeed - In the implementation block
@property (assign,nonatomic) BOOL hasResponseTime; 
@property (assign,nonatomic) int responseTime;                       //@synthesize responseTime=_responseTime - In the implementation block
@property (assign,nonatomic) BOOL hasScreenfulsFromTop; 
@property (assign,nonatomic) int screenfulsFromTop;                  //@synthesize screenfulsFromTop=_screenfulsFromTop - In the implementation block
@property (assign,nonatomic) BOOL hasErrorCode; 
@property (assign,nonatomic) int errorCode;                          //@synthesize errorCode=_errorCode - In the implementation block
-(void)setAdSlotId:(NSString *)arg1 ;
-(void)setHasIsExpanded:(BOOL)arg1 ;
-(BOOL)hasIsExpanded;
-(void)setIsFilled:(BOOL)arg1 ;
-(void)setHasIsFilled:(BOOL)arg1 ;
-(BOOL)hasIsFilled;
-(BOOL)hasAdSlotId;
-(void)setDurationInFeed:(int)arg1 ;
-(void)setHasDurationInFeed:(BOOL)arg1 ;
-(BOOL)hasDurationInFeed;
-(void)setScreenfulsFromTop:(int)arg1 ;
-(void)setHasScreenfulsFromTop:(BOOL)arg1 ;
-(BOOL)hasScreenfulsFromTop;
-(NSString *)adSlotId;
-(int)durationInFeed;
-(int)screenfulsFromTop;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isExpanded;
-(void)setIsExpanded:(BOOL)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(int)responseTime;
-(void)setHasResponseTime:(BOOL)arg1 ;
-(BOOL)hasResponseTime;
-(void)setResponseTime:(int)arg1 ;
-(void)setErrorCode:(int)arg1 ;
-(int)errorCode;
-(void)setHasErrorCode:(BOOL)arg1 ;
-(BOOL)hasErrorCode;
-(BOOL)isFilled;
@end

