/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface NTPBUserOnboardingScreenView : PBCodable <NSCopying> {

	int _onboardingScreenType;
	NSString* _referringSourceApplication;
	NSString* _referringUrl;
	NSString* _userActivityType;
	SCD_Struct_NT7 _has;

}

@property (assign,nonatomic) BOOL hasOnboardingScreenType; 
@property (assign,nonatomic) int onboardingScreenType;                           //@synthesize onboardingScreenType=_onboardingScreenType - In the implementation block
@property (nonatomic,readonly) BOOL hasReferringSourceApplication; 
@property (nonatomic,retain) NSString * referringSourceApplication;              //@synthesize referringSourceApplication=_referringSourceApplication - In the implementation block
@property (nonatomic,readonly) BOOL hasReferringUrl; 
@property (nonatomic,retain) NSString * referringUrl;                            //@synthesize referringUrl=_referringUrl - In the implementation block
@property (nonatomic,readonly) BOOL hasUserActivityType; 
@property (nonatomic,retain) NSString * userActivityType;                        //@synthesize userActivityType=_userActivityType - In the implementation block
-(void)setReferringSourceApplication:(NSString *)arg1 ;
-(void)setReferringUrl:(NSString *)arg1 ;
-(BOOL)hasReferringSourceApplication;
-(BOOL)hasReferringUrl;
-(BOOL)hasUserActivityType;
-(NSString *)referringSourceApplication;
-(NSString *)referringUrl;
-(int)onboardingScreenType;
-(void)setOnboardingScreenType:(int)arg1 ;
-(void)setHasOnboardingScreenType:(BOOL)arg1 ;
-(BOOL)hasOnboardingScreenType;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(NSString *)userActivityType;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setUserActivityType:(NSString *)arg1 ;
@end

