/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSMutableArray;

@interface NTPBAppSessionEnd : PBCodable <NSCopying> {

	long long _appSessionDuration;
	int _channelSubscriptionCount;
	NSMutableArray* _lastVisibleViews;
	int _sessionEndReason;
	int _topicSubscriptionCount;
	SCD_Struct_NT1 _has;

}

@property (assign,nonatomic) BOOL hasSessionEndReason; 
@property (assign,nonatomic) int sessionEndReason;                           //@synthesize sessionEndReason=_sessionEndReason - In the implementation block
@property (nonatomic,retain) NSMutableArray * lastVisibleViews;              //@synthesize lastVisibleViews=_lastVisibleViews - In the implementation block
@property (assign,nonatomic) BOOL hasChannelSubscriptionCount; 
@property (assign,nonatomic) int channelSubscriptionCount;                   //@synthesize channelSubscriptionCount=_channelSubscriptionCount - In the implementation block
@property (assign,nonatomic) BOOL hasTopicSubscriptionCount; 
@property (assign,nonatomic) int topicSubscriptionCount;                     //@synthesize topicSubscriptionCount=_topicSubscriptionCount - In the implementation block
@property (assign,nonatomic) BOOL hasAppSessionDuration; 
@property (assign,nonatomic) long long appSessionDuration;                   //@synthesize appSessionDuration=_appSessionDuration - In the implementation block
-(void)setChannelSubscriptionCount:(int)arg1 ;
-(void)setHasChannelSubscriptionCount:(BOOL)arg1 ;
-(BOOL)hasChannelSubscriptionCount;
-(void)setTopicSubscriptionCount:(int)arg1 ;
-(void)setHasTopicSubscriptionCount:(BOOL)arg1 ;
-(BOOL)hasTopicSubscriptionCount;
-(int)channelSubscriptionCount;
-(int)topicSubscriptionCount;
-(void)addLastVisibleViews:(id)arg1 ;
-(int)sessionEndReason;
-(void)setSessionEndReason:(int)arg1 ;
-(void)setHasSessionEndReason:(BOOL)arg1 ;
-(BOOL)hasSessionEndReason;
-(void)clearLastVisibleViews;
-(unsigned long long)lastVisibleViewsCount;
-(id)lastVisibleViewsAtIndex:(unsigned long long)arg1 ;
-(void)setAppSessionDuration:(long long)arg1 ;
-(void)setHasAppSessionDuration:(BOOL)arg1 ;
-(BOOL)hasAppSessionDuration;
-(NSMutableArray *)lastVisibleViews;
-(void)setLastVisibleViews:(NSMutableArray *)arg1 ;
-(long long)appSessionDuration;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
@end

