/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface NTPBPersonalizationAggregate : PBCodable <NSCopying> {

	double _clicks;
	unsigned long long _eventCount;
	double _impressions;
	unsigned long long _timestamp;
	NSString* _featureKey;
	SCD_Struct_NT1 _has;

}

@property (nonatomic,readonly) BOOL hasFeatureKey; 
@property (nonatomic,retain) NSString * featureKey;                      //@synthesize featureKey=_featureKey - In the implementation block
@property (assign,nonatomic) BOOL hasClicks; 
@property (assign,nonatomic) double clicks;                              //@synthesize clicks=_clicks - In the implementation block
@property (assign,nonatomic) BOOL hasImpressions; 
@property (assign,nonatomic) double impressions;                         //@synthesize impressions=_impressions - In the implementation block
@property (assign,nonatomic) BOOL hasEventCount; 
@property (assign,nonatomic) unsigned long long eventCount;              //@synthesize eventCount=_eventCount - In the implementation block
@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
-(void)setFeatureKey:(NSString *)arg1 ;
-(BOOL)hasFeatureKey;
-(NSString *)featureKey;
-(void)setClicks:(double)arg1 ;
-(void)setHasClicks:(BOOL)arg1 ;
-(BOOL)hasClicks;
-(void)setHasImpressions:(BOOL)arg1 ;
-(BOOL)hasImpressions;
-(void)setEventCount:(unsigned long long)arg1 ;
-(void)setHasEventCount:(BOOL)arg1 ;
-(BOOL)hasEventCount;
-(double)clicks;
-(double)impressions;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(unsigned long long)eventCount;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(void)setImpressions:(double)arg1 ;
@end

