/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/NewsTransport.framework/NewsTransport
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsTransport/NewsTransport-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface NTPBPersonalizationTreatment : PBCodable <NSCopying> {

	double _baselineImpressionPrior;
	double _baselineRatePrior;
	double _decayFactor;
	double _democratizationFactor;
	double _dislikeClickValue;
	double _dislikeClickValueBaseline;
	double _dislikeImpressionValue;
	double _dislikeImpressionValueBaseline;
	double _diversificationPenalty;
	double _existingSubscriptionClickValue;
	double _existingSubscriptionClickValueBaseline;
	double _existingSubscriptionImpressionValue;
	double _existingSubscriptionImpressionValueBaseline;
	double _existingSubscriptionRelatedClickValue;
	double _existingSubscriptionRelatedClickValueBaseline;
	double _existingSubscriptionRelatedImpressionValue;
	double _existingSubscriptionRelatedImpressionValueBaseline;
	long long _extraHeadlinesToShowTheUser;
	double _featureImpressionPrior;
	long long _flowRateDampeningSliceCount;
	double _flowRateDecayFactor;
	double _flowRateDegreeOfDynamism;
	double _flowRateMinimumDampeningFactor;
	double _flowRatePriorWeight;
	double _globalScoreBump;
	double _globalScoreCoefficient;
	double _globalScoreStretchingFactor;
	double _halfLifeCoefficient;
	double _heavyClickClickValue;
	double _heavyClickClickValueBaseline;
	double _heavyClickImpressionValue;
	double _heavyClickImpressionValueBaseline;
	double _heavyClickMinimumDuration;
	double _hourlyFlowRateCeiling;
	double _hourlyFlowRateDampeningFactor;
	double _hourlyFlowRateFloor;
	double _hourlyFlowRateMinimum;
	double _hourlyFlowRatePerSubscription;
	double _hourlyFlowRateSubscriptionCountBuffer;
	double _likeClickValue;
	double _likeClickValueBaseline;
	double _likeImpressionValue;
	double _likeImpressionValueBaseline;
	double _personalizationCoefficient;
	double _presentationClickValue;
	double _presentationClickValueBaseline;
	double _presentationImpressionValue;
	double _presentationImpressionValueBaseline;
	double _publisherDiversificationPenalty;
	long long _publisherTopicIdEventCountMinimum;
	double _saturatedSubscriptionCountFactor;
	double _savedClickValue;
	double _savedClickValueBaseline;
	double _savedImpressionValue;
	double _savedImpressionValueBaseline;
	double _shareClickValue;
	double _shareClickValueBaseline;
	double _shareImpressionValue;
	double _shareImpressionValueBaseline;
	long long _sliceTimeInterval;
	double _subscribeClickValue;
	double _subscribeClickValueBaseline;
	double _subscribeImpressionValue;
	double _subscribeImpressionValueBaseline;
	double _subscriptionRelatedClickValue;
	double _subscriptionRelatedClickValueBaseline;
	double _subscriptionRelatedImpressionValue;
	double _subscriptionRelatedImpressionValueBaseline;
	double _subscriptionVoteCoefficient;
	double _tappedClickValue;
	double _tappedClickValueBaseline;
	double _tappedImpressionValue;
	double _tappedImpressionValueBaseline;
	long long _treatmentId;
	double _unsubscribeClickValue;
	double _unsubscribeClickValueBaseline;
	double _unsubscribeImpressionValue;
	double _unsubscribeImpressionValueBaseline;
	double _visitClickValue;
	double _visitClickValueBaseline;
	double _visitImpressionValue;
	double _visitImpressionValueBaseline;
	double _weakClickClickValue;
	double _weakClickClickValueBaseline;
	double _weakClickImpressionValue;
	double _weakClickImpressionValueBaseline;
	BOOL _globalScoreRankingEnabled;
	BOOL _hardAgeBeforePublisherDiversification;
	SCD_Struct_NT19 _has;

}

@property (assign,nonatomic) BOOL hasTreatmentId; 
@property (assign,nonatomic) long long treatmentId;                                                   //@synthesize treatmentId=_treatmentId - In the implementation block
@property (assign,nonatomic) BOOL hasDecayFactor; 
@property (assign,nonatomic) double decayFactor;                                                      //@synthesize decayFactor=_decayFactor - In the implementation block
@property (assign,nonatomic) BOOL hasBaselineImpressionPrior; 
@property (assign,nonatomic) double baselineImpressionPrior;                                          //@synthesize baselineImpressionPrior=_baselineImpressionPrior - In the implementation block
@property (assign,nonatomic) BOOL hasBaselineRatePrior; 
@property (assign,nonatomic) double baselineRatePrior;                                                //@synthesize baselineRatePrior=_baselineRatePrior - In the implementation block
@property (assign,nonatomic) BOOL hasFeatureImpressionPrior; 
@property (assign,nonatomic) double featureImpressionPrior;                                           //@synthesize featureImpressionPrior=_featureImpressionPrior - In the implementation block
@property (assign,nonatomic) BOOL hasGlobalScoreRankingEnabled; 
@property (assign,nonatomic) BOOL globalScoreRankingEnabled;                                          //@synthesize globalScoreRankingEnabled=_globalScoreRankingEnabled - In the implementation block
@property (assign,nonatomic) BOOL hasGlobalScoreBump; 
@property (assign,nonatomic) double globalScoreBump;                                                  //@synthesize globalScoreBump=_globalScoreBump - In the implementation block
@property (assign,nonatomic) BOOL hasSubscriptionVoteCoefficient; 
@property (assign,nonatomic) double subscriptionVoteCoefficient;                                      //@synthesize subscriptionVoteCoefficient=_subscriptionVoteCoefficient - In the implementation block
@property (assign,nonatomic) BOOL hasPersonalizationCoefficient; 
@property (assign,nonatomic) double personalizationCoefficient;                                       //@synthesize personalizationCoefficient=_personalizationCoefficient - In the implementation block
@property (assign,nonatomic) BOOL hasGlobalScoreCoefficient; 
@property (assign,nonatomic) double globalScoreCoefficient;                                           //@synthesize globalScoreCoefficient=_globalScoreCoefficient - In the implementation block
@property (assign,nonatomic) BOOL hasPublisherTopicIdEventCountMinimum; 
@property (assign,nonatomic) long long publisherTopicIdEventCountMinimum;                             //@synthesize publisherTopicIdEventCountMinimum=_publisherTopicIdEventCountMinimum - In the implementation block
@property (assign,nonatomic) BOOL hasPresentationImpressionValue; 
@property (assign,nonatomic) double presentationImpressionValue;                                      //@synthesize presentationImpressionValue=_presentationImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasHeavyClickImpressionValue; 
@property (assign,nonatomic) double heavyClickImpressionValue;                                        //@synthesize heavyClickImpressionValue=_heavyClickImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasLikeImpressionValue; 
@property (assign,nonatomic) double likeImpressionValue;                                              //@synthesize likeImpressionValue=_likeImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasShareImpressionValue; 
@property (assign,nonatomic) double shareImpressionValue;                                             //@synthesize shareImpressionValue=_shareImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasSavedImpressionValue; 
@property (assign,nonatomic) double savedImpressionValue;                                             //@synthesize savedImpressionValue=_savedImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasSubscribeImpressionValue; 
@property (assign,nonatomic) double subscribeImpressionValue;                                         //@synthesize subscribeImpressionValue=_subscribeImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasTappedImpressionValue; 
@property (assign,nonatomic) double tappedImpressionValue;                                            //@synthesize tappedImpressionValue=_tappedImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasWeakClickImpressionValue; 
@property (assign,nonatomic) double weakClickImpressionValue;                                         //@synthesize weakClickImpressionValue=_weakClickImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasUnsubscribeImpressionValue; 
@property (assign,nonatomic) double unsubscribeImpressionValue;                                       //@synthesize unsubscribeImpressionValue=_unsubscribeImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasVisitImpressionValue; 
@property (assign,nonatomic) double visitImpressionValue;                                             //@synthesize visitImpressionValue=_visitImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasDislikeImpressionValue; 
@property (assign,nonatomic) double dislikeImpressionValue;                                           //@synthesize dislikeImpressionValue=_dislikeImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasPresentationClickValue; 
@property (assign,nonatomic) double presentationClickValue;                                           //@synthesize presentationClickValue=_presentationClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasHeavyClickClickValue; 
@property (assign,nonatomic) double heavyClickClickValue;                                             //@synthesize heavyClickClickValue=_heavyClickClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasLikeClickValue; 
@property (assign,nonatomic) double likeClickValue;                                                   //@synthesize likeClickValue=_likeClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasShareClickValue; 
@property (assign,nonatomic) double shareClickValue;                                                  //@synthesize shareClickValue=_shareClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasSavedClickValue; 
@property (assign,nonatomic) double savedClickValue;                                                  //@synthesize savedClickValue=_savedClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasSubscribeClickValue; 
@property (assign,nonatomic) double subscribeClickValue;                                              //@synthesize subscribeClickValue=_subscribeClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasTappedClickValue; 
@property (assign,nonatomic) double tappedClickValue;                                                 //@synthesize tappedClickValue=_tappedClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasWeakClickClickValue; 
@property (assign,nonatomic) double weakClickClickValue;                                              //@synthesize weakClickClickValue=_weakClickClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasUnsubscribeClickValue; 
@property (assign,nonatomic) double unsubscribeClickValue;                                            //@synthesize unsubscribeClickValue=_unsubscribeClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasVisitClickValue; 
@property (assign,nonatomic) double visitClickValue;                                                  //@synthesize visitClickValue=_visitClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasDislikeClickValue; 
@property (assign,nonatomic) double dislikeClickValue;                                                //@synthesize dislikeClickValue=_dislikeClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasHourlyFlowRateMinimum; 
@property (assign,nonatomic) double hourlyFlowRateMinimum;                                            //@synthesize hourlyFlowRateMinimum=_hourlyFlowRateMinimum - In the implementation block
@property (assign,nonatomic) BOOL hasHourlyFlowRateSubscriptionCountBuffer; 
@property (assign,nonatomic) double hourlyFlowRateSubscriptionCountBuffer;                            //@synthesize hourlyFlowRateSubscriptionCountBuffer=_hourlyFlowRateSubscriptionCountBuffer - In the implementation block
@property (assign,nonatomic) BOOL hasHourlyFlowRateDampeningFactor; 
@property (assign,nonatomic) double hourlyFlowRateDampeningFactor;                                    //@synthesize hourlyFlowRateDampeningFactor=_hourlyFlowRateDampeningFactor - In the implementation block
@property (assign,nonatomic) BOOL hasDemocratizationFactor; 
@property (assign,nonatomic) double democratizationFactor;                                            //@synthesize democratizationFactor=_democratizationFactor - In the implementation block
@property (assign,nonatomic) BOOL hasSliceTimeInterval; 
@property (assign,nonatomic) long long sliceTimeInterval;                                             //@synthesize sliceTimeInterval=_sliceTimeInterval - In the implementation block
@property (assign,nonatomic) BOOL hasFlowRateDampeningSliceCount; 
@property (assign,nonatomic) long long flowRateDampeningSliceCount;                                   //@synthesize flowRateDampeningSliceCount=_flowRateDampeningSliceCount - In the implementation block
@property (assign,nonatomic) BOOL hasFlowRateMinimumDampeningFactor; 
@property (assign,nonatomic) double flowRateMinimumDampeningFactor;                                   //@synthesize flowRateMinimumDampeningFactor=_flowRateMinimumDampeningFactor - In the implementation block
@property (assign,nonatomic) BOOL hasHalfLifeCoefficient; 
@property (assign,nonatomic) double halfLifeCoefficient;                                              //@synthesize halfLifeCoefficient=_halfLifeCoefficient - In the implementation block
@property (assign,nonatomic) BOOL hasDiversificationPenalty; 
@property (assign,nonatomic) double diversificationPenalty;                                           //@synthesize diversificationPenalty=_diversificationPenalty - In the implementation block
@property (assign,nonatomic) BOOL hasHeavyClickMinimumDuration; 
@property (assign,nonatomic) double heavyClickMinimumDuration;                                        //@synthesize heavyClickMinimumDuration=_heavyClickMinimumDuration - In the implementation block
@property (assign,nonatomic) BOOL hasSubscriptionRelatedImpressionValue; 
@property (assign,nonatomic) double subscriptionRelatedImpressionValue;                               //@synthesize subscriptionRelatedImpressionValue=_subscriptionRelatedImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasSubscriptionRelatedClickValue; 
@property (assign,nonatomic) double subscriptionRelatedClickValue;                                    //@synthesize subscriptionRelatedClickValue=_subscriptionRelatedClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasHourlyFlowRatePerSubscription; 
@property (assign,nonatomic) double hourlyFlowRatePerSubscription;                                    //@synthesize hourlyFlowRatePerSubscription=_hourlyFlowRatePerSubscription - In the implementation block
@property (assign,nonatomic) BOOL hasExtraHeadlinesToShowTheUser; 
@property (assign,nonatomic) long long extraHeadlinesToShowTheUser;                                   //@synthesize extraHeadlinesToShowTheUser=_extraHeadlinesToShowTheUser - In the implementation block
@property (assign,nonatomic) BOOL hasFlowRateDegreeOfDynamism; 
@property (assign,nonatomic) double flowRateDegreeOfDynamism;                                         //@synthesize flowRateDegreeOfDynamism=_flowRateDegreeOfDynamism - In the implementation block
@property (assign,nonatomic) BOOL hasFlowRateDecayFactor; 
@property (assign,nonatomic) double flowRateDecayFactor;                                              //@synthesize flowRateDecayFactor=_flowRateDecayFactor - In the implementation block
@property (assign,nonatomic) BOOL hasFlowRatePriorWeight; 
@property (assign,nonatomic) double flowRatePriorWeight;                                              //@synthesize flowRatePriorWeight=_flowRatePriorWeight - In the implementation block
@property (assign,nonatomic) BOOL hasPresentationImpressionValueBaseline; 
@property (assign,nonatomic) double presentationImpressionValueBaseline;                              //@synthesize presentationImpressionValueBaseline=_presentationImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasHeavyClickImpressionValueBaseline; 
@property (assign,nonatomic) double heavyClickImpressionValueBaseline;                                //@synthesize heavyClickImpressionValueBaseline=_heavyClickImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasLikeImpressionValueBaseline; 
@property (assign,nonatomic) double likeImpressionValueBaseline;                                      //@synthesize likeImpressionValueBaseline=_likeImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasShareImpressionValueBaseline; 
@property (assign,nonatomic) double shareImpressionValueBaseline;                                     //@synthesize shareImpressionValueBaseline=_shareImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasSavedImpressionValueBaseline; 
@property (assign,nonatomic) double savedImpressionValueBaseline;                                     //@synthesize savedImpressionValueBaseline=_savedImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasSubscribeImpressionValueBaseline; 
@property (assign,nonatomic) double subscribeImpressionValueBaseline;                                 //@synthesize subscribeImpressionValueBaseline=_subscribeImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasTappedImpressionValueBaseline; 
@property (assign,nonatomic) double tappedImpressionValueBaseline;                                    //@synthesize tappedImpressionValueBaseline=_tappedImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasWeakClickImpressionValueBaseline; 
@property (assign,nonatomic) double weakClickImpressionValueBaseline;                                 //@synthesize weakClickImpressionValueBaseline=_weakClickImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasUnsubscribeImpressionValueBaseline; 
@property (assign,nonatomic) double unsubscribeImpressionValueBaseline;                               //@synthesize unsubscribeImpressionValueBaseline=_unsubscribeImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasVisitImpressionValueBaseline; 
@property (assign,nonatomic) double visitImpressionValueBaseline;                                     //@synthesize visitImpressionValueBaseline=_visitImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasDislikeImpressionValueBaseline; 
@property (assign,nonatomic) double dislikeImpressionValueBaseline;                                   //@synthesize dislikeImpressionValueBaseline=_dislikeImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasSubscriptionRelatedImpressionValueBaseline; 
@property (assign,nonatomic) double subscriptionRelatedImpressionValueBaseline;                       //@synthesize subscriptionRelatedImpressionValueBaseline=_subscriptionRelatedImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasPresentationClickValueBaseline; 
@property (assign,nonatomic) double presentationClickValueBaseline;                                   //@synthesize presentationClickValueBaseline=_presentationClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasHeavyClickClickValueBaseline; 
@property (assign,nonatomic) double heavyClickClickValueBaseline;                                     //@synthesize heavyClickClickValueBaseline=_heavyClickClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasLikeClickValueBaseline; 
@property (assign,nonatomic) double likeClickValueBaseline;                                           //@synthesize likeClickValueBaseline=_likeClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasShareClickValueBaseline; 
@property (assign,nonatomic) double shareClickValueBaseline;                                          //@synthesize shareClickValueBaseline=_shareClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasSavedClickValueBaseline; 
@property (assign,nonatomic) double savedClickValueBaseline;                                          //@synthesize savedClickValueBaseline=_savedClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasSubscribeClickValueBaseline; 
@property (assign,nonatomic) double subscribeClickValueBaseline;                                      //@synthesize subscribeClickValueBaseline=_subscribeClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasTappedClickValueBaseline; 
@property (assign,nonatomic) double tappedClickValueBaseline;                                         //@synthesize tappedClickValueBaseline=_tappedClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasWeakClickClickValueBaseline; 
@property (assign,nonatomic) double weakClickClickValueBaseline;                                      //@synthesize weakClickClickValueBaseline=_weakClickClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasUnsubscribeClickValueBaseline; 
@property (assign,nonatomic) double unsubscribeClickValueBaseline;                                    //@synthesize unsubscribeClickValueBaseline=_unsubscribeClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasVisitClickValueBaseline; 
@property (assign,nonatomic) double visitClickValueBaseline;                                          //@synthesize visitClickValueBaseline=_visitClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasDislikeClickValueBaseline; 
@property (assign,nonatomic) double dislikeClickValueBaseline;                                        //@synthesize dislikeClickValueBaseline=_dislikeClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasSubscriptionRelatedClickValueBaseline; 
@property (assign,nonatomic) double subscriptionRelatedClickValueBaseline;                            //@synthesize subscriptionRelatedClickValueBaseline=_subscriptionRelatedClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionImpressionValue; 
@property (assign,nonatomic) double existingSubscriptionImpressionValue;                              //@synthesize existingSubscriptionImpressionValue=_existingSubscriptionImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionClickValue; 
@property (assign,nonatomic) double existingSubscriptionClickValue;                                   //@synthesize existingSubscriptionClickValue=_existingSubscriptionClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionImpressionValueBaseline; 
@property (assign,nonatomic) double existingSubscriptionImpressionValueBaseline;                      //@synthesize existingSubscriptionImpressionValueBaseline=_existingSubscriptionImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionClickValueBaseline; 
@property (assign,nonatomic) double existingSubscriptionClickValueBaseline;                           //@synthesize existingSubscriptionClickValueBaseline=_existingSubscriptionClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionRelatedImpressionValue; 
@property (assign,nonatomic) double existingSubscriptionRelatedImpressionValue;                       //@synthesize existingSubscriptionRelatedImpressionValue=_existingSubscriptionRelatedImpressionValue - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionRelatedClickValue; 
@property (assign,nonatomic) double existingSubscriptionRelatedClickValue;                            //@synthesize existingSubscriptionRelatedClickValue=_existingSubscriptionRelatedClickValue - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionRelatedImpressionValueBaseline; 
@property (assign,nonatomic) double existingSubscriptionRelatedImpressionValueBaseline;               //@synthesize existingSubscriptionRelatedImpressionValueBaseline=_existingSubscriptionRelatedImpressionValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasExistingSubscriptionRelatedClickValueBaseline; 
@property (assign,nonatomic) double existingSubscriptionRelatedClickValueBaseline;                    //@synthesize existingSubscriptionRelatedClickValueBaseline=_existingSubscriptionRelatedClickValueBaseline - In the implementation block
@property (assign,nonatomic) BOOL hasGlobalScoreStretchingFactor; 
@property (assign,nonatomic) double globalScoreStretchingFactor;                                      //@synthesize globalScoreStretchingFactor=_globalScoreStretchingFactor - In the implementation block
@property (assign,nonatomic) BOOL hasHourlyFlowRateFloor; 
@property (assign,nonatomic) double hourlyFlowRateFloor;                                              //@synthesize hourlyFlowRateFloor=_hourlyFlowRateFloor - In the implementation block
@property (assign,nonatomic) BOOL hasHourlyFlowRateCeiling; 
@property (assign,nonatomic) double hourlyFlowRateCeiling;                                            //@synthesize hourlyFlowRateCeiling=_hourlyFlowRateCeiling - In the implementation block
@property (assign,nonatomic) BOOL hasSaturatedSubscriptionCountFactor; 
@property (assign,nonatomic) double saturatedSubscriptionCountFactor;                                 //@synthesize saturatedSubscriptionCountFactor=_saturatedSubscriptionCountFactor - In the implementation block
@property (assign,nonatomic) BOOL hasPublisherDiversificationPenalty; 
@property (assign,nonatomic) double publisherDiversificationPenalty;                                  //@synthesize publisherDiversificationPenalty=_publisherDiversificationPenalty - In the implementation block
@property (assign,nonatomic) BOOL hasHardAgeBeforePublisherDiversification; 
@property (assign,nonatomic) BOOL hardAgeBeforePublisherDiversification;                              //@synthesize hardAgeBeforePublisherDiversification=_hardAgeBeforePublisherDiversification - In the implementation block
-(void)setTreatmentId:(long long)arg1 ;
-(void)setHasTreatmentId:(BOOL)arg1 ;
-(BOOL)hasTreatmentId;
-(long long)treatmentId;
-(void)setDecayFactor:(double)arg1 ;
-(void)setHasDecayFactor:(BOOL)arg1 ;
-(BOOL)hasDecayFactor;
-(void)setBaselineImpressionPrior:(double)arg1 ;
-(void)setHasBaselineImpressionPrior:(BOOL)arg1 ;
-(BOOL)hasBaselineImpressionPrior;
-(void)setBaselineRatePrior:(double)arg1 ;
-(void)setHasBaselineRatePrior:(BOOL)arg1 ;
-(BOOL)hasBaselineRatePrior;
-(void)setFeatureImpressionPrior:(double)arg1 ;
-(void)setHasFeatureImpressionPrior:(BOOL)arg1 ;
-(BOOL)hasFeatureImpressionPrior;
-(void)setGlobalScoreRankingEnabled:(BOOL)arg1 ;
-(void)setHasGlobalScoreRankingEnabled:(BOOL)arg1 ;
-(BOOL)hasGlobalScoreRankingEnabled;
-(void)setGlobalScoreBump:(double)arg1 ;
-(void)setHasGlobalScoreBump:(BOOL)arg1 ;
-(BOOL)hasGlobalScoreBump;
-(void)setSubscriptionVoteCoefficient:(double)arg1 ;
-(void)setHasSubscriptionVoteCoefficient:(BOOL)arg1 ;
-(BOOL)hasSubscriptionVoteCoefficient;
-(void)setPersonalizationCoefficient:(double)arg1 ;
-(void)setHasPersonalizationCoefficient:(BOOL)arg1 ;
-(BOOL)hasPersonalizationCoefficient;
-(void)setGlobalScoreCoefficient:(double)arg1 ;
-(void)setHasGlobalScoreCoefficient:(BOOL)arg1 ;
-(BOOL)hasGlobalScoreCoefficient;
-(void)setPublisherTopicIdEventCountMinimum:(long long)arg1 ;
-(void)setHasPublisherTopicIdEventCountMinimum:(BOOL)arg1 ;
-(BOOL)hasPublisherTopicIdEventCountMinimum;
-(void)setPresentationImpressionValue:(double)arg1 ;
-(void)setHasPresentationImpressionValue:(BOOL)arg1 ;
-(BOOL)hasPresentationImpressionValue;
-(void)setHeavyClickImpressionValue:(double)arg1 ;
-(void)setHasHeavyClickImpressionValue:(BOOL)arg1 ;
-(BOOL)hasHeavyClickImpressionValue;
-(void)setLikeImpressionValue:(double)arg1 ;
-(void)setHasLikeImpressionValue:(BOOL)arg1 ;
-(BOOL)hasLikeImpressionValue;
-(void)setShareImpressionValue:(double)arg1 ;
-(void)setHasShareImpressionValue:(BOOL)arg1 ;
-(BOOL)hasShareImpressionValue;
-(void)setSavedImpressionValue:(double)arg1 ;
-(void)setHasSavedImpressionValue:(BOOL)arg1 ;
-(BOOL)hasSavedImpressionValue;
-(void)setSubscribeImpressionValue:(double)arg1 ;
-(void)setHasSubscribeImpressionValue:(BOOL)arg1 ;
-(BOOL)hasSubscribeImpressionValue;
-(void)setTappedImpressionValue:(double)arg1 ;
-(void)setHasTappedImpressionValue:(BOOL)arg1 ;
-(BOOL)hasTappedImpressionValue;
-(void)setWeakClickImpressionValue:(double)arg1 ;
-(void)setHasWeakClickImpressionValue:(BOOL)arg1 ;
-(BOOL)hasWeakClickImpressionValue;
-(void)setUnsubscribeImpressionValue:(double)arg1 ;
-(void)setHasUnsubscribeImpressionValue:(BOOL)arg1 ;
-(BOOL)hasUnsubscribeImpressionValue;
-(void)setVisitImpressionValue:(double)arg1 ;
-(void)setHasVisitImpressionValue:(BOOL)arg1 ;
-(BOOL)hasVisitImpressionValue;
-(void)setDislikeImpressionValue:(double)arg1 ;
-(void)setHasDislikeImpressionValue:(BOOL)arg1 ;
-(BOOL)hasDislikeImpressionValue;
-(void)setPresentationClickValue:(double)arg1 ;
-(void)setHasPresentationClickValue:(BOOL)arg1 ;
-(BOOL)hasPresentationClickValue;
-(void)setHeavyClickClickValue:(double)arg1 ;
-(void)setHasHeavyClickClickValue:(BOOL)arg1 ;
-(BOOL)hasHeavyClickClickValue;
-(void)setLikeClickValue:(double)arg1 ;
-(void)setHasLikeClickValue:(BOOL)arg1 ;
-(BOOL)hasLikeClickValue;
-(void)setShareClickValue:(double)arg1 ;
-(void)setHasShareClickValue:(BOOL)arg1 ;
-(BOOL)hasShareClickValue;
-(void)setSavedClickValue:(double)arg1 ;
-(void)setHasSavedClickValue:(BOOL)arg1 ;
-(BOOL)hasSavedClickValue;
-(void)setSubscribeClickValue:(double)arg1 ;
-(void)setHasSubscribeClickValue:(BOOL)arg1 ;
-(BOOL)hasSubscribeClickValue;
-(void)setTappedClickValue:(double)arg1 ;
-(void)setHasTappedClickValue:(BOOL)arg1 ;
-(BOOL)hasTappedClickValue;
-(void)setWeakClickClickValue:(double)arg1 ;
-(void)setHasWeakClickClickValue:(BOOL)arg1 ;
-(BOOL)hasWeakClickClickValue;
-(void)setUnsubscribeClickValue:(double)arg1 ;
-(void)setHasUnsubscribeClickValue:(BOOL)arg1 ;
-(BOOL)hasUnsubscribeClickValue;
-(void)setVisitClickValue:(double)arg1 ;
-(void)setHasVisitClickValue:(BOOL)arg1 ;
-(BOOL)hasVisitClickValue;
-(void)setDislikeClickValue:(double)arg1 ;
-(void)setHasDislikeClickValue:(BOOL)arg1 ;
-(BOOL)hasDislikeClickValue;
-(void)setHourlyFlowRateMinimum:(double)arg1 ;
-(void)setHasHourlyFlowRateMinimum:(BOOL)arg1 ;
-(BOOL)hasHourlyFlowRateMinimum;
-(void)setHourlyFlowRateSubscriptionCountBuffer:(double)arg1 ;
-(void)setHasHourlyFlowRateSubscriptionCountBuffer:(BOOL)arg1 ;
-(BOOL)hasHourlyFlowRateSubscriptionCountBuffer;
-(void)setHourlyFlowRateDampeningFactor:(double)arg1 ;
-(void)setHasHourlyFlowRateDampeningFactor:(BOOL)arg1 ;
-(BOOL)hasHourlyFlowRateDampeningFactor;
-(void)setDemocratizationFactor:(double)arg1 ;
-(void)setHasDemocratizationFactor:(BOOL)arg1 ;
-(BOOL)hasDemocratizationFactor;
-(void)setSliceTimeInterval:(long long)arg1 ;
-(void)setHasSliceTimeInterval:(BOOL)arg1 ;
-(BOOL)hasSliceTimeInterval;
-(void)setFlowRateDampeningSliceCount:(long long)arg1 ;
-(void)setHasFlowRateDampeningSliceCount:(BOOL)arg1 ;
-(BOOL)hasFlowRateDampeningSliceCount;
-(void)setFlowRateMinimumDampeningFactor:(double)arg1 ;
-(void)setHasFlowRateMinimumDampeningFactor:(BOOL)arg1 ;
-(BOOL)hasFlowRateMinimumDampeningFactor;
-(void)setHalfLifeCoefficient:(double)arg1 ;
-(void)setHasHalfLifeCoefficient:(BOOL)arg1 ;
-(BOOL)hasHalfLifeCoefficient;
-(void)setDiversificationPenalty:(double)arg1 ;
-(void)setHasDiversificationPenalty:(BOOL)arg1 ;
-(BOOL)hasDiversificationPenalty;
-(void)setHeavyClickMinimumDuration:(double)arg1 ;
-(void)setHasHeavyClickMinimumDuration:(BOOL)arg1 ;
-(BOOL)hasHeavyClickMinimumDuration;
-(void)setSubscriptionRelatedImpressionValue:(double)arg1 ;
-(void)setHasSubscriptionRelatedImpressionValue:(BOOL)arg1 ;
-(BOOL)hasSubscriptionRelatedImpressionValue;
-(void)setSubscriptionRelatedClickValue:(double)arg1 ;
-(void)setHasSubscriptionRelatedClickValue:(BOOL)arg1 ;
-(BOOL)hasSubscriptionRelatedClickValue;
-(void)setHourlyFlowRatePerSubscription:(double)arg1 ;
-(void)setHasHourlyFlowRatePerSubscription:(BOOL)arg1 ;
-(BOOL)hasHourlyFlowRatePerSubscription;
-(void)setExtraHeadlinesToShowTheUser:(long long)arg1 ;
-(void)setHasExtraHeadlinesToShowTheUser:(BOOL)arg1 ;
-(BOOL)hasExtraHeadlinesToShowTheUser;
-(void)setFlowRateDegreeOfDynamism:(double)arg1 ;
-(void)setHasFlowRateDegreeOfDynamism:(BOOL)arg1 ;
-(BOOL)hasFlowRateDegreeOfDynamism;
-(void)setFlowRateDecayFactor:(double)arg1 ;
-(void)setHasFlowRateDecayFactor:(BOOL)arg1 ;
-(BOOL)hasFlowRateDecayFactor;
-(void)setFlowRatePriorWeight:(double)arg1 ;
-(void)setHasFlowRatePriorWeight:(BOOL)arg1 ;
-(BOOL)hasFlowRatePriorWeight;
-(void)setPresentationImpressionValueBaseline:(double)arg1 ;
-(void)setHasPresentationImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasPresentationImpressionValueBaseline;
-(void)setHeavyClickImpressionValueBaseline:(double)arg1 ;
-(void)setHasHeavyClickImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasHeavyClickImpressionValueBaseline;
-(void)setLikeImpressionValueBaseline:(double)arg1 ;
-(void)setHasLikeImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasLikeImpressionValueBaseline;
-(void)setShareImpressionValueBaseline:(double)arg1 ;
-(void)setHasShareImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasShareImpressionValueBaseline;
-(void)setSavedImpressionValueBaseline:(double)arg1 ;
-(void)setHasSavedImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasSavedImpressionValueBaseline;
-(void)setSubscribeImpressionValueBaseline:(double)arg1 ;
-(void)setHasSubscribeImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasSubscribeImpressionValueBaseline;
-(void)setTappedImpressionValueBaseline:(double)arg1 ;
-(void)setHasTappedImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasTappedImpressionValueBaseline;
-(void)setWeakClickImpressionValueBaseline:(double)arg1 ;
-(void)setHasWeakClickImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasWeakClickImpressionValueBaseline;
-(void)setUnsubscribeImpressionValueBaseline:(double)arg1 ;
-(void)setHasUnsubscribeImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasUnsubscribeImpressionValueBaseline;
-(void)setVisitImpressionValueBaseline:(double)arg1 ;
-(void)setHasVisitImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasVisitImpressionValueBaseline;
-(void)setDislikeImpressionValueBaseline:(double)arg1 ;
-(void)setHasDislikeImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasDislikeImpressionValueBaseline;
-(void)setSubscriptionRelatedImpressionValueBaseline:(double)arg1 ;
-(void)setHasSubscriptionRelatedImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasSubscriptionRelatedImpressionValueBaseline;
-(void)setPresentationClickValueBaseline:(double)arg1 ;
-(void)setHasPresentationClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasPresentationClickValueBaseline;
-(void)setHeavyClickClickValueBaseline:(double)arg1 ;
-(void)setHasHeavyClickClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasHeavyClickClickValueBaseline;
-(void)setLikeClickValueBaseline:(double)arg1 ;
-(void)setHasLikeClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasLikeClickValueBaseline;
-(void)setShareClickValueBaseline:(double)arg1 ;
-(void)setHasShareClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasShareClickValueBaseline;
-(void)setSavedClickValueBaseline:(double)arg1 ;
-(void)setHasSavedClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasSavedClickValueBaseline;
-(void)setSubscribeClickValueBaseline:(double)arg1 ;
-(void)setHasSubscribeClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasSubscribeClickValueBaseline;
-(void)setTappedClickValueBaseline:(double)arg1 ;
-(void)setHasTappedClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasTappedClickValueBaseline;
-(void)setWeakClickClickValueBaseline:(double)arg1 ;
-(void)setHasWeakClickClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasWeakClickClickValueBaseline;
-(void)setUnsubscribeClickValueBaseline:(double)arg1 ;
-(void)setHasUnsubscribeClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasUnsubscribeClickValueBaseline;
-(void)setVisitClickValueBaseline:(double)arg1 ;
-(void)setHasVisitClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasVisitClickValueBaseline;
-(void)setDislikeClickValueBaseline:(double)arg1 ;
-(void)setHasDislikeClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasDislikeClickValueBaseline;
-(void)setSubscriptionRelatedClickValueBaseline:(double)arg1 ;
-(void)setHasSubscriptionRelatedClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasSubscriptionRelatedClickValueBaseline;
-(void)setExistingSubscriptionImpressionValue:(double)arg1 ;
-(void)setHasExistingSubscriptionImpressionValue:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionImpressionValue;
-(void)setExistingSubscriptionClickValue:(double)arg1 ;
-(void)setHasExistingSubscriptionClickValue:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionClickValue;
-(void)setExistingSubscriptionImpressionValueBaseline:(double)arg1 ;
-(void)setHasExistingSubscriptionImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionImpressionValueBaseline;
-(void)setExistingSubscriptionClickValueBaseline:(double)arg1 ;
-(void)setHasExistingSubscriptionClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionClickValueBaseline;
-(void)setExistingSubscriptionRelatedImpressionValue:(double)arg1 ;
-(void)setHasExistingSubscriptionRelatedImpressionValue:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionRelatedImpressionValue;
-(void)setExistingSubscriptionRelatedClickValue:(double)arg1 ;
-(void)setHasExistingSubscriptionRelatedClickValue:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionRelatedClickValue;
-(void)setExistingSubscriptionRelatedImpressionValueBaseline:(double)arg1 ;
-(void)setHasExistingSubscriptionRelatedImpressionValueBaseline:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionRelatedImpressionValueBaseline;
-(void)setExistingSubscriptionRelatedClickValueBaseline:(double)arg1 ;
-(void)setHasExistingSubscriptionRelatedClickValueBaseline:(BOOL)arg1 ;
-(BOOL)hasExistingSubscriptionRelatedClickValueBaseline;
-(void)setGlobalScoreStretchingFactor:(double)arg1 ;
-(void)setHasGlobalScoreStretchingFactor:(BOOL)arg1 ;
-(BOOL)hasGlobalScoreStretchingFactor;
-(void)setHourlyFlowRateFloor:(double)arg1 ;
-(void)setHasHourlyFlowRateFloor:(BOOL)arg1 ;
-(BOOL)hasHourlyFlowRateFloor;
-(void)setHourlyFlowRateCeiling:(double)arg1 ;
-(void)setHasHourlyFlowRateCeiling:(BOOL)arg1 ;
-(BOOL)hasHourlyFlowRateCeiling;
-(void)setSaturatedSubscriptionCountFactor:(double)arg1 ;
-(void)setHasSaturatedSubscriptionCountFactor:(BOOL)arg1 ;
-(BOOL)hasSaturatedSubscriptionCountFactor;
-(void)setPublisherDiversificationPenalty:(double)arg1 ;
-(void)setHasPublisherDiversificationPenalty:(BOOL)arg1 ;
-(BOOL)hasPublisherDiversificationPenalty;
-(void)setHardAgeBeforePublisherDiversification:(BOOL)arg1 ;
-(void)setHasHardAgeBeforePublisherDiversification:(BOOL)arg1 ;
-(BOOL)hasHardAgeBeforePublisherDiversification;
-(double)decayFactor;
-(double)baselineImpressionPrior;
-(double)baselineRatePrior;
-(double)featureImpressionPrior;
-(BOOL)globalScoreRankingEnabled;
-(double)globalScoreBump;
-(double)subscriptionVoteCoefficient;
-(double)personalizationCoefficient;
-(double)globalScoreCoefficient;
-(long long)publisherTopicIdEventCountMinimum;
-(double)presentationImpressionValue;
-(double)heavyClickImpressionValue;
-(double)likeImpressionValue;
-(double)shareImpressionValue;
-(double)savedImpressionValue;
-(double)subscribeImpressionValue;
-(double)tappedImpressionValue;
-(double)weakClickImpressionValue;
-(double)unsubscribeImpressionValue;
-(double)visitImpressionValue;
-(double)dislikeImpressionValue;
-(double)presentationClickValue;
-(double)heavyClickClickValue;
-(double)likeClickValue;
-(double)shareClickValue;
-(double)savedClickValue;
-(double)subscribeClickValue;
-(double)tappedClickValue;
-(double)weakClickClickValue;
-(double)unsubscribeClickValue;
-(double)visitClickValue;
-(double)dislikeClickValue;
-(double)hourlyFlowRateMinimum;
-(double)hourlyFlowRateSubscriptionCountBuffer;
-(double)hourlyFlowRateDampeningFactor;
-(double)democratizationFactor;
-(long long)sliceTimeInterval;
-(long long)flowRateDampeningSliceCount;
-(double)flowRateMinimumDampeningFactor;
-(double)halfLifeCoefficient;
-(double)diversificationPenalty;
-(double)heavyClickMinimumDuration;
-(double)subscriptionRelatedImpressionValue;
-(double)subscriptionRelatedClickValue;
-(double)hourlyFlowRatePerSubscription;
-(long long)extraHeadlinesToShowTheUser;
-(double)flowRateDegreeOfDynamism;
-(double)flowRateDecayFactor;
-(double)flowRatePriorWeight;
-(double)presentationImpressionValueBaseline;
-(double)heavyClickImpressionValueBaseline;
-(double)likeImpressionValueBaseline;
-(double)shareImpressionValueBaseline;
-(double)savedImpressionValueBaseline;
-(double)subscribeImpressionValueBaseline;
-(double)tappedImpressionValueBaseline;
-(double)weakClickImpressionValueBaseline;
-(double)unsubscribeImpressionValueBaseline;
-(double)visitImpressionValueBaseline;
-(double)dislikeImpressionValueBaseline;
-(double)subscriptionRelatedImpressionValueBaseline;
-(double)presentationClickValueBaseline;
-(double)heavyClickClickValueBaseline;
-(double)likeClickValueBaseline;
-(double)shareClickValueBaseline;
-(double)savedClickValueBaseline;
-(double)subscribeClickValueBaseline;
-(double)tappedClickValueBaseline;
-(double)weakClickClickValueBaseline;
-(double)unsubscribeClickValueBaseline;
-(double)visitClickValueBaseline;
-(double)dislikeClickValueBaseline;
-(double)subscriptionRelatedClickValueBaseline;
-(double)existingSubscriptionImpressionValue;
-(double)existingSubscriptionClickValue;
-(double)existingSubscriptionImpressionValueBaseline;
-(double)existingSubscriptionClickValueBaseline;
-(double)existingSubscriptionRelatedImpressionValue;
-(double)existingSubscriptionRelatedClickValue;
-(double)existingSubscriptionRelatedImpressionValueBaseline;
-(double)existingSubscriptionRelatedClickValueBaseline;
-(double)globalScoreStretchingFactor;
-(double)hourlyFlowRateFloor;
-(double)hourlyFlowRateCeiling;
-(double)saturatedSubscriptionCountFactor;
-(double)publisherDiversificationPenalty;
-(BOOL)hardAgeBeforePublisherDiversification;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
@end

