/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift._SwiftNativeNSSet.h>
#import <libswiftCore.dylib/Swift._NSSetCoreType.h>

@interface Swift._NativeSetStorageOwnerBase : Swift._SwiftNativeNSSet <Swift._NSSetCoreType>

@property (readonly,nonatomic) long long count; 
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3 ;
-(long long)count;
-(id)init;
-(id)objectEnumerator;
-(id)copyWithZone:(void*)arg1 ;
-(id)initWithObjects:(const id*)arg1 count:(long long)arg2 ;
-(id)member:(id)arg1 ;
@end

