/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift._SwiftNativeNSEnumerator.h>
#import <libswiftCore.dylib/Swift._NSEnumeratorType.h>

@interface Swift._NativeDictionaryStorageKeyNSEnumeratorBase : Swift._SwiftNativeNSEnumerator <Swift._NSEnumeratorType>
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3 ;
-(id)init;
-(id)nextObject;
@end

