/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Swift._stdlib_ReturnAutoreleasedDummy : _UKNOWN_SUPERCLASS_
-(id)returnsAutoreleased:(id)arg1 ;
-(void)initializeReturnAutoreleased;
-(id)init;
@end

