/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol Swift._NSArrayCoreType <Swift._NSCopyingType,Swift._NSFastEnumerationType>
@property (readonly,nonatomic) long long count; 
@required
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3;
-(long long)count;
-(id)objectAtIndex:(long long)arg1;
-(void)getObjects:(id*)arg1 range:(SCD_Struct_Sw1)arg2;

@end

