/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift._SwiftNativeNSDictionary.h>
#import <libswiftCore.dylib/Swift._NSDictionaryCoreType.h>

@interface Swift._NativeDictionaryStorageOwnerBase : Swift._SwiftNativeNSDictionary <Swift._NSDictionaryCoreType>

@property (readonly,nonatomic) long long count; 
-(void)bridgedAllKeysAndValues:(id*)arg1 :(id*)arg2 ;
-(long long)countByEnumeratingWithState:(SCD_Struct_Sw0*)arg1 objects:(id*)arg2 count:(long long)arg3 ;
-(long long)count;
-(id)init;
-(id)objectForKey:(id)arg1 ;
-(id)copyWithZone:(void*)arg1 ;
-(id)initWithObjects:(const id*)arg1 forKeys:(const void*)arg2 count:(long long)arg3 ;
-(id)keyEnumerator;
-(void)getObjects:(id*)arg1 andKeys:(id*)arg2 ;
@end

