/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libobjc.A.dylib/NSObject.h>

@class NSString;

@interface SwiftObject : _UKNOWN_SUPERCLASS_ <NSObject> {

	void* magic_isa;
	long long magic_refCount;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)class;
+(id)alloc;
+(BOOL)respondsToSelector:(SEL)arg1 ;
+(BOOL)isMemberOfClass:(Class)arg1 ;
+(BOOL)conformsToProtocol:(id)arg1 ;
+(id)retain;
+(void)release;
+(id)autorelease;
+(unsigned long long)retainCount;
+(Class)superclass;
+(id)description;
+(id)debugDescription;
+(BOOL)isSubclassOfClass:(Class)arg1 ;
+(id)allocWithZone:(NSZone*)arg1 ;
+(void)initialize;
+(BOOL)_isDeallocating;
+(BOOL)allowsWeakReference;
+(BOOL)instancesRespondToSelector:(SEL)arg1 ;
+(BOOL)retainWeakReference;
+(BOOL)_tryRetain;
-(BOOL)isNSDate__;
-(unsigned long long)_cfTypeID;
-(BOOL)isNSSet__;
-(BOOL)isNSValue__;
-(id)_copyDescription;
-(BOOL)isNSOrderedSet__;
-(Class)class;
-(void)dealloc;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(BOOL)isKindOfClass:(Class)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)self;
-(id)performSelector:(SEL)arg1 ;
-(id)performSelector:(SEL)arg1 withObject:(id)arg2 ;
-(id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3 ;
-(BOOL)isProxy;
-(BOOL)isMemberOfClass:(Class)arg1 ;
-(BOOL)conformsToProtocol:(id)arg1 ;
-(id)retain;
-(void)release;
-(id)autorelease;
-(unsigned long long)retainCount;
-(NSZone*)zone;
-(unsigned long long)hash;
-(Class)superclass;
-(NSString *)description;
-(NSString *)debugDescription;
-(void)doesNotRecognizeSelector:(SEL)arg1 ;
-(BOOL)_isDeallocating;
-(BOOL)allowsWeakReference;
-(BOOL)retainWeakReference;
-(BOOL)_tryRetain;
-(BOOL)isNSDictionary__;
-(BOOL)isNSArray__;
-(BOOL)isNSString__;
-(BOOL)isNSNumber__;
-(BOOL)isNSData__;
@end

