/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:00 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Calculator.app/Frameworks/libswiftCore.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libswiftCore.dylib/libswiftCore.dylib-Structs.h>
#import <libswiftCore.dylib/Swift._SwiftNativeNSString.h>

@interface Swift._NSContiguousString : Swift._SwiftNativeNSString {

	 _core;

}
-(unsigned short*)_fastCharacterContents;
-(id)initWithCoder:(id)arg1 ;
-(id)init;
-(id)substringFromIndex:(long long)arg1 ;
-(id)copy;
-(long long)length;
-(id)substringWithRange:(SCD_Struct_Sw1)arg1 ;
-(unsigned short)characterAtIndex:(long long)arg1 ;
-(id)substringToIndex:(long long)arg1 ;
-(void)getCharacters:(unsigned short*)arg1 range:(SCD_Struct_Sw1)arg2 ;
@end

