/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:10 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ACAccountStore, ACAccountType, NSArray;

@interface SVAccountManager : NSObject {

	ACAccountStore* accountStore;
	ACAccountType* serverAccountType;
	NSArray* cachedServerAccounts;

}
+(id)sharedManager;
-(id)serverDocumentsAccounts;
-(void)accountStoreDidChange;
-(void)getServerDocumentsAccounts;
-(id)init;
-(id)accountWithIdentifier:(id)arg1 ;
@end

