/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:10 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UILabel, UIButton;

@interface SVErrorView : UIView {

	UILabel* _titleLabel;
	UILabel* _detailLabel;
	UIButton* _retryButton;

}

@property (assign,nonatomic,__weak) UILabel * titleLabel;                //@synthesize titleLabel=_titleLabel - In the implementation block
@property (assign,nonatomic,__weak) UILabel * detailLabel;               //@synthesize detailLabel=_detailLabel - In the implementation block
@property (assign,nonatomic,__weak) UIButton * retryButton;              //@synthesize retryButton=_retryButton - In the implementation block
-(UIButton *)retryButton;
-(void)setRetryButton:(UIButton *)arg1 ;
-(id)init;
-(void)traitCollectionDidChange:(id)arg1 ;
-(UILabel *)titleLabel;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(UILabel *)detailLabel;
-(void)setDetailLabel:(UILabel *)arg1 ;
@end

