/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:09 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/Podcasts.app/Frameworks/IMUtil.framework/IMUtil
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IMJSONUtil : NSObject
+(id)fromJSONData:(id)arg1 ;
+(id)fromJSONString:(id)arg1 ;
+(id)toJSONString:(id)arg1 ;
@end

