/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SXAdControllerDelegate, SXAdControllerDataSource, OS_dispatch_queue;
#import <Silex/Silex-Structs.h>
@class NSDictionary, SXContext, SXDocument, NSMutableArray, NSObject, NSMutableDictionary;

@interface SXAdController : NSObject {

	BOOL _didLoadFirstBannerView;
	NSDictionary* _campaignData;
	id<SXAdControllerDelegate> _delegate;
	id<SXAdControllerDataSource> _dataSource;
	SXContext* _context;
	SXDocument* _document;
	NSMutableArray* _componentViewsDisplayingAds;
	NSObject*<OS_dispatch_queue> _bannerViewsQueue;
	NSMutableDictionary* _bannerViews;

}

@property (nonatomic,readonly) NSDictionary * campaignData;                               //@synthesize campaignData=_campaignData - In the implementation block
@property (assign,nonatomic,__weak) id<SXAdControllerDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<SXAdControllerDataSource> dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (nonatomic,__weak,readonly) SXContext * context;                                //@synthesize context=_context - In the implementation block
@property (nonatomic,readonly) SXDocument * document;                                     //@synthesize document=_document - In the implementation block
@property (nonatomic,readonly) NSMutableArray * componentViewsDisplayingAds;              //@synthesize componentViewsDisplayingAds=_componentViewsDisplayingAds - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> bannerViewsQueue;               //@synthesize bannerViewsQueue=_bannerViewsQueue - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * bannerViews;                           //@synthesize bannerViews=_bannerViews - In the implementation block
@property (assign,nonatomic) BOOL didLoadFirstBannerView;                                 //@synthesize didLoadFirstBannerView=_didLoadFirstBannerView - In the implementation block
+(id)debugAdvertismentSettings;
+(void)setDebugAdvertisingSettings:(id)arg1 ;
+(BOOL)isDebugModeEnabled;
+(void)setDebugModeEnabled:(BOOL)arg1 ;
-(void)transitionToSizeWithVisibleBounds:(CGRect)arg1 ;
-(NSDictionary *)campaignData;
-(NSMutableArray *)componentViewsDisplayingAds;
-(BOOL)isRect:(CGRect)arg1 withinScreenFullOfRect:(CGRect)arg2 viewport:(CGSize)arg3 ;
-(BOOL)componentViewWithinScreenHeightOfViewport:(id)arg1 ;
-(BOOL)didLoadFirstBannerView;
-(BOOL)isDisplayingAdsWithinScreenfullOfComponentView:(id)arg1 ;
-(BOOL)isComponentViewWithinFirstViewport:(id)arg1 ;
-(BOOL)allowComponentViewInFirstViewport:(id)arg1 ;
-(void)setDidLoadFirstBannerView:(BOOL)arg1 ;
-(NSObject*<OS_dispatch_queue>)bannerViewsQueue;
-(NSMutableDictionary *)bannerViews;
-(void)setBannerViews:(NSMutableDictionary *)arg1 ;
-(BOOL)component:(id)arg1 isLastComponentInComponents:(id)arg2 ;
-(BOOL)shouldRequestBannerViewForComponentView:(id)arg1 ;
-(/*^block*/id)bannerViewForComponentView:(id)arg1 adType:(unsigned long long)arg2 completionBlock:(/*^block*/id)arg3 ;
-(/*^block*/id)prerollWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)componentView:(id)arg1 didLoadBannerView:(id)arg2 ;
-(void)componentView:(id)arg1 didUnloadBannerView:(id)arg2 ;
-(void)componentView:(id)arg1 failedToLoadBannerView:(id)arg2 error:(id)arg3 ;
-(CGRect)frameForBannerViewForComponentIdentifier:(id)arg1 ;
-(void)setBannerViewsQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)setDataSource:(id<SXAdControllerDataSource>)arg1 ;
-(void)setDelegate:(id<SXAdControllerDelegate>)arg1 ;
-(id<SXAdControllerDataSource>)dataSource;
-(id<SXAdControllerDelegate>)delegate;
-(void)reset;
-(SXContext *)context;
-(id)initWithContext:(id)arg1 ;
-(SXDocument *)document;
@end

