/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SXAnimatedImageViewCacheDelegate, OS_dispatch_queue;
#import <Silex/Silex-Structs.h>
@class SXAnimatedImage, NSObject, NSMutableArray, NSMutableIndexSet;

@interface SXAnimatedImageViewCache : NSObject {

	BOOL _cachingEnabled;
	id<SXAnimatedImageViewCacheDelegate> _delegate;
	SXAnimatedImage* _animatedImage;
	long long _singleImageByteSize;
	unsigned long long _lastRequestedIndex;
	NSObject*<OS_dispatch_queue> _decodingQueue;
	NSObject*<OS_dispatch_queue> _serializationQueue;
	unsigned long long _numberOfCachedImages;
	NSMutableArray* _cachedImages;
	NSMutableIndexSet* _indicesToCache;

}

@property (assign,nonatomic,__weak) id<SXAnimatedImageViewCacheDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) SXAnimatedImage * animatedImage;                            //@synthesize animatedImage=_animatedImage - In the implementation block
@property (assign) BOOL cachingEnabled;                                                         //@synthesize cachingEnabled=_cachingEnabled - In the implementation block
@property (assign) long long singleImageByteSize;                                               //@synthesize singleImageByteSize=_singleImageByteSize - In the implementation block
@property (assign) unsigned long long lastRequestedIndex;                                       //@synthesize lastRequestedIndex=_lastRequestedIndex - In the implementation block
@property (nonatomic,readonly) unsigned long long maxCacheSize; 
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> decodingQueue;                      //@synthesize decodingQueue=_decodingQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> serializationQueue;                 //@synthesize serializationQueue=_serializationQueue - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfCachedImages;                           //@synthesize numberOfCachedImages=_numberOfCachedImages - In the implementation block
@property (nonatomic,readonly) NSMutableArray * cachedImages;                                   //@synthesize cachedImages=_cachedImages - In the implementation block
@property (nonatomic,readonly) NSMutableIndexSet * indicesToCache;                              //@synthesize indicesToCache=_indicesToCache - In the implementation block
-(id)imageForFrameIndex:(unsigned long long)arg1 ;
-(NSObject*<OS_dispatch_queue>)serializationQueue;
-(void)prepareCache;
-(NSMutableIndexSet *)indicesToCache;
-(void)cacheNextImage;
-(void)setLastRequestedIndex:(unsigned long long)arg1 ;
-(unsigned long long)numberOfCachedImages;
-(void)setNumberOfCachedImages:(unsigned long long)arg1 ;
-(void)decreaseCacheSize;
-(void)restoreCacheSize;
-(long long)singleImageByteSize;
-(void)setSingleImageByteSize:(long long)arg1 ;
-(NSObject*<OS_dispatch_queue>)decodingQueue;
-(id)decodeImageFromSource:(CGImageSourceRef)arg1 index:(unsigned long long)arg2 ;
-(void)checkCacheSize;
-(unsigned long long)maxCacheSize;
-(unsigned long long)lastRequestedIndex;
-(void)prepareImageForFrameIndex:(unsigned long long)arg1 ;
-(unsigned long long)nearestCachedFrameIndexForFrameIndex:(unsigned long long)arg1 ;
-(long long)cacheStatusForFrameIndex:(unsigned long long)arg1 ;
-(void)setDelegate:(id<SXAnimatedImageViewCacheDelegate>)arg1 ;
-(id)init;
-(id<SXAnimatedImageViewCacheDelegate>)delegate;
-(NSMutableArray *)cachedImages;
-(void)prune;
-(void)setAnimatedImage:(SXAnimatedImage *)arg1 ;
-(SXAnimatedImage *)animatedImage;
-(void)setCachingEnabled:(BOOL)arg1 ;
-(BOOL)cachingEnabled;
@end

