/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <TSReading/TSWPEditingControllerDelegate.h>
#import <Silex/SXTextTangierInteractiveCanvasControllerDelegate.h>

@protocol SXAutoSizedCanvasControllerDelegate;
@class TSKDocumentRoot, SXTextTangierInteractiveCanvasController, SXTextTangierCanvasViewController, TSDCanvasView, NSString;

@interface SXAutoSizedCanvasController : NSObject <TSWPEditingControllerDelegate, SXTextTangierInteractiveCanvasControllerDelegate> {

	TSKDocumentRoot* _documentRoot;
	CGRect _frame;
	id<SXAutoSizedCanvasControllerDelegate> _delegate;
	SXTextTangierInteractiveCanvasController* _icc;
	SXTextTangierCanvasViewController* _cvc;
	double _lineHeight;

}

@property (assign,nonatomic,__weak) id<SXAutoSizedCanvasControllerDelegate> delegate;                   //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) SXTextTangierInteractiveCanvasController * icc;                          //@synthesize icc=_icc - In the implementation block
@property (nonatomic,readonly) SXTextTangierCanvasViewController * cvc;                                 //@synthesize cvc=_cvc - In the implementation block
@property (nonatomic,readonly) TSDCanvasView * canvasView; 
@property (nonatomic,readonly) double lineHeight;                                                       //@synthesize lineHeight=_lineHeight - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) BOOL editorShouldAlwaysBeInParagraphMode; 
@property (nonatomic,readonly) BOOL editorAllowsEditMenu; 
@property (nonatomic,readonly) BOOL editorAllowsMagnifier; 
@property (nonatomic,readonly) BOOL editorAllowsParagraphMode; 
@property (nonatomic,readonly) BOOL editorAllowsKeyboard; 
@property (nonatomic,readonly) BOOL editorAllowsCaret; 
@property (nonatomic,readonly) BOOL editorAllowsHyperlinkInteraction; 
@property (nonatomic,readonly) BOOL editorAllowsRubyInteraction; 
@property (nonatomic,readonly) BOOL editorAllowsListInteraction; 
@property (nonatomic,readonly) TSKDocumentRoot * documentRoot; 
@property (nonatomic,readonly) BOOL isCanvasInteractive; 
@property (nonatomic,readonly) BOOL isPrintingCanvas; 
@property (nonatomic,readonly) BOOL spellCheckingSupported; 
@property (nonatomic,readonly) BOOL spellCheckingSuppressed; 
@property (nonatomic,readonly) BOOL shouldResizeCanvasToScrollView; 
@property (nonatomic,readonly) BOOL shouldClipToScrollViewBoundsInVisibleBounds; 
@property (nonatomic,readonly) BOOL shouldShowTextOverflowGlyphs; 
@property (nonatomic,readonly) BOOL shouldShowInstructionalText; 
@property (nonatomic,readonly) BOOL shouldPopKnobsOutsideEnclosingScrollView; 
@property (nonatomic,readonly) CGSize sizeOfScrollViewEnclosingCanvas; 
@property (nonatomic,readonly) BOOL allowEditMenuToAppear; 
@property (nonatomic,readonly) BOOL allowTextEditingToBegin; 
@property (nonatomic,readonly) BOOL interactiveCanvasControllerAllowsHyperlinkInteraction; 
-(SXTextTangierCanvasViewController *)cvc;
-(void)invalidateLayoutsAndFrames;
-(CGSize)sizeThatFits;
-(void)interactiveCanvasController:(id)arg1 didTriggerAction:(id)arg2 info:(id)arg3 range:(NSRange)arg4 touchPoint:(CGPoint)arg5 touchAndHold:(BOOL)arg6 ;
-(BOOL)allowCopy;
-(BOOL)allowSelectionPopover;
-(TSDCanvasView *)canvasView;
-(BOOL)isCanvasInteractive;
-(id)initWithDocumentRoot:(id)arg1 ;
-(CGRect)interactiveCanvasController:(id)arg1 expandVisibleBoundsForTiling:(CGRect)arg2 ;
-(Class)wpEditorClassOverride;
-(BOOL)editorAllowsEditMenu;
-(BOOL)editorAllowsCaret;
-(void)setDelegate:(id<SXAutoSizedCanvasControllerDelegate>)arg1 ;
-(id<SXAutoSizedCanvasControllerDelegate>)delegate;
-(double)lineHeight;
-(BOOL)allowHighlighting;
-(void)teardown;
-(TSKDocumentRoot *)documentRoot;
-(SXTextTangierInteractiveCanvasController *)icc;
@end

