/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentView.h>

@class AVPlayerViewController, SXAVPlayer, SXAudioComponentOverlayView, SXMediaExposureEvent;

@interface SXAudioComponentView : SXComponentView {

	BOOL _audioHasPlayed;
	BOOL _startPlaybackWhenReady;
	AVPlayerViewController* _playerViewController;
	SXAVPlayer* _player;
	SXAudioComponentOverlayView* _overlayView;
	SXMediaExposureEvent* _activeExposureEvent;
	SCD_Struct_SX9 _playbackStartTime;
	SCD_Struct_SX9 _timePlayed;

}

@property (nonatomic,retain) AVPlayerViewController * playerViewController;              //@synthesize playerViewController=_playerViewController - In the implementation block
@property (nonatomic,retain) SXAVPlayer * player;                                        //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) SXAudioComponentOverlayView * overlayView;                  //@synthesize overlayView=_overlayView - In the implementation block
@property (assign,nonatomic) BOOL audioHasPlayed;                                        //@synthesize audioHasPlayed=_audioHasPlayed - In the implementation block
@property (nonatomic,retain) SXMediaExposureEvent * activeExposureEvent;                 //@synthesize activeExposureEvent=_activeExposureEvent - In the implementation block
@property (assign,nonatomic) BOOL startPlaybackWhenReady;                                //@synthesize startPlaybackWhenReady=_startPlaybackWhenReady - In the implementation block
@property (assign,nonatomic) SCD_Struct_SX9 playbackStartTime;                           //@synthesize playbackStartTime=_playbackStartTime - In the implementation block
@property (assign,nonatomic) SCD_Struct_SX9 timePlayed;                                  //@synthesize timePlayed=_timePlayed - In the implementation block
-(void)renderContents;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 context:(id)arg3 ;
-(void)presentComponent;
-(void)setPlaybackStartTime:(SCD_Struct_SX9)arg1 ;
-(SCD_Struct_SX9)playbackStartTime;
-(void)finishMediaExposureEvent;
-(void)createMediaExposureEventIfLoadedAndVisible;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(SXMediaExposureEvent *)activeExposureEvent;
-(void)setActiveExposureEvent:(SXMediaExposureEvent *)arg1 ;
-(void)playButtonTapped:(id)arg1 ;
-(void)setStartPlaybackWhenReady:(BOOL)arg1 ;
-(void)loadAudio;
-(void)setupPlayerViewControllerWithPlayer:(id)arg1 ;
-(BOOL)shouldAutoStartPlayback;
-(void)playbackFinished;
-(BOOL)startPlaybackWhenReady;
-(BOOL)audioHasPlayed;
-(void)submitMediaEngageCompleteEvent;
-(void)submitMediaEngageEventForUserAction:(unsigned long long)arg1 ;
-(void)setAudioHasPlayed:(BOOL)arg1 ;
-(void)hidePlaybackControls;
-(void)showPlaybackControls;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)willMoveToWindow:(id)arg1 ;
-(SCD_Struct_SX9)timePlayed;
-(void)setTimePlayed:(SCD_Struct_SX9)arg1 ;
-(void)setPlayerViewController:(AVPlayerViewController *)arg1 ;
-(AVPlayerViewController *)playerViewController;
-(void)setOverlayView:(SXAudioComponentOverlayView *)arg1 ;
-(SXAudioComponentOverlayView *)overlayView;
-(void)setPlayer:(SXAVPlayer *)arg1 ;
-(SXAVPlayer *)player;
-(void)playbackStarted;
-(void)playbackPaused;
-(void)playbackResumed;
-(void)loadImage;
@end

