/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSHashTable;

@interface SXAudioSession : NSObject {

	BOOL _audioSessionActive;
	NSHashTable* _players;

}

@property (nonatomic,readonly) NSHashTable * players;                                          //@synthesize players=_players - In the implementation block
@property (assign,getter=isAudioSessionActive,nonatomic) BOOL audioSessionActive;              //@synthesize audioSessionActive=_audioSessionActive - In the implementation block
+(id)sharedSession;
-(void)addInterestForPlayer:(id)arg1 ;
-(void)removeInterestForPlayer:(id)arg1 ;
-(BOOL)shouldActivateAudioSession;
-(void)activateAudioSessionCategory;
-(BOOL)canDeactivateAudioSession;
-(void)deactivateAudioSessionCategory;
-(BOOL)needsToSetupAudioSessionCategory;
-(void)setupAudioSessionCategory;
-(id)init;
-(BOOL)isAudioSessionActive;
-(void)setAudioSessionActive:(BOOL)arg1 ;
-(NSHashTable *)players;
@end

