/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:05 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXActionHandler.h>
#import <Silex/MFMessageComposeViewControllerDelegate.h>
#import <libobjc.A.dylib/CNContactViewControllerDelegate.h>

@class UIAlertAction, UIViewController, NSString;

@interface SXCallActionHandler : SXActionHandler <MFMessageComposeViewControllerDelegate, CNContactViewControllerDelegate> {

	UIAlertAction* _callAction;
	UIAlertAction* _facetimeAction;
	UIAlertAction* _messageAction;
	UIAlertAction* _addToContactsAction;
	UIAlertAction* _copyAction;
	UIViewController* _presentedModalViewController;

}

@property (nonatomic,readonly) UIAlertAction * callAction;                                 //@synthesize callAction=_callAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * facetimeAction;                             //@synthesize facetimeAction=_facetimeAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * messageAction;                              //@synthesize messageAction=_messageAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * addToContactsAction;                        //@synthesize addToContactsAction=_addToContactsAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * copyAction;                                 //@synthesize copyAction=_copyAction - In the implementation block
@property (nonatomic,retain) UIViewController * presentedModalViewController;              //@synthesize presentedModalViewController=_presentedModalViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(UIAlertAction *)callAction;
-(UIAlertAction *)messageAction;
-(UIAlertAction *)addToContactsAction;
-(UIAlertAction *)copyAction;
-(long long)alertControllerStyle;
-(BOOL)canMakeCalls;
-(void)makeCall;
-(BOOL)canMakeFacetimeAudioCalls;
-(void)makeFaceTimeCall;
-(void)addToContacts;
-(UIViewController *)presentedModalViewController;
-(void)setPresentedModalViewController:(UIViewController *)arg1 ;
-(void)dismissPresentedViewController;
-(id)alertActions;
-(id)title;
-(id)message;
-(void)messageComposeViewController:(id)arg1 didFinishWithResult:(int)arg2 ;
-(void)copyToPasteboard;
-(UIAlertAction *)facetimeAction;
-(void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2 ;
-(BOOL)contactViewController:(id)arg1 shouldPerformDefaultActionForContactProperty:(id)arg2 ;
-(void)sendMessage;
@end

