/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXJSONObject.h>

@class SXComponentAnimation, NSString, SXComponentAnchor, SXJSONArray;

@interface SXComponent : SXJSONObject {

	SXComponentAnimation* backingAnimation;

}

@property (nonatomic,readonly) NSString * identifier; 
@property (nonatomic,readonly) NSString * type; 
@property (nonatomic,readonly) NSString * layout; 
@property (nonatomic,readonly) NSString * style; 
@property (nonatomic,readonly) int role; 
@property (nonatomic,readonly) SXComponentAnchor * anchor; 
@property (nonatomic,readonly) SXJSONArray * behaviors; 
@property (nonatomic,readonly) SXComponentAnimation * animation; 
@property (nonatomic,retain) SXComponentAnimation * backingAnimation; 
+(/*^block*/id)valueClassBlockForPropertyWithName:(id)arg1 ;
-(SXComponentAnimation *)animation;
-(SXJSONArray *)behaviors;
-(SXComponentAnchor *)anchor;
-(NSString *)style;
-(NSString *)layout;
-(NSString *)type;
-(NSString *)identifier;
-(SXComponentAnimation *)backingAnimation;
-(void)setBackingAnimation:(SXComponentAnimation *)arg1 ;
-(id)animationWithValue:(id)arg1 withType:(int)arg2 ;
-(id)description;
-(id)classification;
-(int)role;
@end

