/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class SXDocumentLayout, NSString;

@interface SXColumnLayout : NSObject <NSCopying> {

	SXDocumentLayout* _documentLayout;
	long long _layoutWidth;
	long long _leftMargin;
	long long _rightMargin;
	long long _topPadding;
	long long _bottomPadding;
	long long _gutter;
	unsigned long long _numberOfColumns;
	double _columnWidth;
	long long _leftColumnOffset;
	long long _rightColumnOffset;
	double _leftInset;
	double _rightInset;
	double _minimumHeight;
	NSString* _contentSizeCategory;
	unsigned long long _layoutColumns;
	CGSize _viewportSize;

}

@property (nonatomic,readonly) CGSize viewportSize;                              //@synthesize viewportSize=_viewportSize - In the implementation block
@property (nonatomic,readonly) SXDocumentLayout * documentLayout;                //@synthesize documentLayout=_documentLayout - In the implementation block
@property (nonatomic,readonly) long long layoutWidth;                            //@synthesize layoutWidth=_layoutWidth - In the implementation block
@property (nonatomic,readonly) long long leftMargin;                             //@synthesize leftMargin=_leftMargin - In the implementation block
@property (nonatomic,readonly) long long rightMargin;                            //@synthesize rightMargin=_rightMargin - In the implementation block
@property (assign,nonatomic) long long topPadding;                               //@synthesize topPadding=_topPadding - In the implementation block
@property (assign,nonatomic) long long bottomPadding;                            //@synthesize bottomPadding=_bottomPadding - In the implementation block
@property (nonatomic,readonly) long long gutter;                                 //@synthesize gutter=_gutter - In the implementation block
@property (nonatomic,readonly) unsigned long long numberOfColumns;               //@synthesize numberOfColumns=_numberOfColumns - In the implementation block
@property (nonatomic,readonly) double columnWidth;                               //@synthesize columnWidth=_columnWidth - In the implementation block
@property (assign,nonatomic) long long leftColumnOffset;                         //@synthesize leftColumnOffset=_leftColumnOffset - In the implementation block
@property (assign,nonatomic) long long rightColumnOffset;                        //@synthesize rightColumnOffset=_rightColumnOffset - In the implementation block
@property (assign,nonatomic) double leftInset;                                   //@synthesize leftInset=_leftInset - In the implementation block
@property (assign,nonatomic) double rightInset;                                  //@synthesize rightInset=_rightInset - In the implementation block
@property (assign,nonatomic) double minimumHeight;                               //@synthesize minimumHeight=_minimumHeight - In the implementation block
@property (nonatomic,copy,readonly) NSString * contentSizeCategory;              //@synthesize contentSizeCategory=_contentSizeCategory - In the implementation block
@property (nonatomic,readonly) unsigned long long layoutColumns;                 //@synthesize layoutColumns=_layoutColumns - In the implementation block
-(long long)gutter;
-(NSRange)convertColumnRange:(NSRange)arg1 minimumColumnLength:(long long)arg2 ;
-(double)widthForColumnRange:(NSRange)arg1 ignoreMargin:(unsigned long long)arg2 ignoreGutter:(unsigned long long)arg3 ;
-(double)xPositionForColumnIndex:(long long)arg1 ignoreMargin:(unsigned long long)arg2 ignoreGutter:(unsigned long long)arg3 ;
-(id)initWithViewportSize:(CGSize)arg1 documentLayout:(id)arg2 numberOfLayoutColumns:(unsigned long long)arg3 leftMargin:(double)arg4 rightMargin:(double)arg5 numberOfColumns:(unsigned long long)arg6 columnWidth:(double)arg7 andContentSizeCategory:(id)arg8 ;
-(id)columnLayoutForComponentBlueprint:(id)arg1 ;
-(SXDocumentLayout *)documentLayout;
-(long long)leftColumnOffset;
-(void)setLeftColumnOffset:(long long)arg1 ;
-(long long)rightColumnOffset;
-(void)setRightColumnOffset:(long long)arg1 ;
-(unsigned long long)layoutColumns;
-(NSString *)contentSizeCategory;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(unsigned long long)numberOfColumns;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)rightMargin;
-(double)columnWidth;
-(long long)topPadding;
-(long long)layoutWidth;
-(CGSize)viewportSize;
-(long long)bottomPadding;
-(void)setBottomPadding:(long long)arg1 ;
-(double)minimumHeight;
-(void)setMinimumHeight:(double)arg1 ;
-(void)setTopPadding:(long long)arg1 ;
-(long long)leftMargin;
-(double)leftInset;
-(double)rightInset;
-(void)setLeftInset:(double)arg1 ;
-(void)setRightInset:(double)arg1 ;
@end

