/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>

@class SXComponent, SXComponentLayout, SXLayoutBlueprint, SXComponentSizer, NSDictionary;

@interface SXComponentBlueprint : NSObject <NSCoding> {

	BOOL _hasValidSize;
	BOOL _hasValidPosition;
	SXComponent* _component;
	SXComponentLayout* _componentLayout;
	SXLayoutBlueprint* _parentLayoutBlueprint;
	SXComponentSizer* _componentSizer;
	NSDictionary* _infoFromLayouting;
	NSRange _columnRange;
	CGSize _suggestedSizeAfterInvalidation;
	CGRect _frame;
	CGRect _contentFrame;
	CGRect _absoluteFrame;
	UIEdgeInsets _contentInsets;

}

@property (assign,nonatomic) NSRange columnRange;                                           //@synthesize columnRange=_columnRange - In the implementation block
@property (nonatomic,readonly) SXComponent * component;                                     //@synthesize component=_component - In the implementation block
@property (nonatomic,readonly) SXComponentLayout * componentLayout;                         //@synthesize componentLayout=_componentLayout - In the implementation block
@property (nonatomic,__weak,readonly) SXLayoutBlueprint * rootLayoutBlueprint; 
@property (assign,nonatomic,__weak) SXLayoutBlueprint * parentLayoutBlueprint;              //@synthesize parentLayoutBlueprint=_parentLayoutBlueprint - In the implementation block
@property (nonatomic,readonly) BOOL hasValidLayout; 
@property (assign,nonatomic) BOOL hasValidSize;                                             //@synthesize hasValidSize=_hasValidSize - In the implementation block
@property (assign,nonatomic) BOOL hasValidPosition;                                         //@synthesize hasValidPosition=_hasValidPosition - In the implementation block
@property (assign,nonatomic) CGRect frame;                                                  //@synthesize frame=_frame - In the implementation block
@property (assign,nonatomic) CGRect contentFrame;                                           //@synthesize contentFrame=_contentFrame - In the implementation block
@property (assign,nonatomic) CGRect absoluteFrame;                                          //@synthesize absoluteFrame=_absoluteFrame - In the implementation block
@property (assign,nonatomic) UIEdgeInsets contentInsets;                                    //@synthesize contentInsets=_contentInsets - In the implementation block
@property (nonatomic,retain) SXComponentSizer * componentSizer;                             //@synthesize componentSizer=_componentSizer - In the implementation block
@property (assign,nonatomic) CGSize suggestedSizeAfterInvalidation;                         //@synthesize suggestedSizeAfterInvalidation=_suggestedSizeAfterInvalidation - In the implementation block
@property (nonatomic,readonly) NSDictionary * infoFromLayouting;                            //@synthesize infoFromLayouting=_infoFromLayouting - In the implementation block
-(CGRect)absoluteFrame;
-(SXComponentLayout *)componentLayout;
-(NSRange)columnRange;
-(SXLayoutBlueprint *)parentLayoutBlueprint;
-(BOOL)hasValidLayout;
-(NSDictionary *)infoFromLayouting;
-(SXComponentSizer *)componentSizer;
-(void)setColumnRange:(NSRange)arg1 ;
-(void)setParentLayoutBlueprint:(SXLayoutBlueprint *)arg1 ;
-(void)setAbsoluteFrame:(CGRect)arg1 ;
-(void)setHasValidSize:(BOOL)arg1 ;
-(void)setHasValidPosition:(BOOL)arg1 ;
-(BOOL)hasValidPosition;
-(BOOL)hasValidSize;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 componentSizer:(id)arg3 ;
-(void)updateSize:(CGSize)arg1 ;
-(void)updatePosition:(CGPoint)arg1 ;
-(UIEdgeInsets)contentInsetsForComponentWidth:(double)arg1 ;
-(SXLayoutBlueprint *)rootLayoutBlueprint;
-(void)storeInformationForRenderingPhase:(id)arg1 ;
-(void)setComponentSizer:(SXComponentSizer *)arg1 ;
-(CGSize)suggestedSizeAfterInvalidation;
-(void)setSuggestedSizeAfterInvalidation:(CGSize)arg1 ;
-(void)invalidateSize;
-(void)invalidatePosition;
-(CGRect)contentFrame;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(CGRect)frame;
-(id)description;
-(UIEdgeInsets)contentInsets;
-(void)setContentInsets:(UIEdgeInsets)arg1 ;
-(void)invalidateLayout;
-(SXComponent *)component;
-(void)setContentFrame:(CGRect)arg1 ;
@end

