/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SXComponentStyle, SXComponentView, SXGradientView, SXImageFillView, SXVideoPlayerView, UIView;

@interface SXComponentStyleRenderer : NSObject {

	SXComponentStyle* _componentStyle;
	SXComponentView* _componentView;
	SXGradientView* _gradientView;
	SXImageFillView* _imageFillView;
	SXVideoPlayerView* _playerView;
	UIView* _fillClippingView;
	UIView* _borderContainerView;

}

@property (nonatomic,__weak,readonly) SXComponentStyle * componentStyle;              //@synthesize componentStyle=_componentStyle - In the implementation block
@property (nonatomic,__weak,readonly) SXComponentView * componentView;                //@synthesize componentView=_componentView - In the implementation block
@property (nonatomic,retain) SXGradientView * gradientView;                           //@synthesize gradientView=_gradientView - In the implementation block
@property (nonatomic,retain) SXImageFillView * imageFillView;                         //@synthesize imageFillView=_imageFillView - In the implementation block
@property (nonatomic,retain) SXVideoPlayerView * playerView;                          //@synthesize playerView=_playerView - In the implementation block
@property (nonatomic,retain) UIView * fillClippingView;                               //@synthesize fillClippingView=_fillClippingView - In the implementation block
@property (nonatomic,retain) UIView * borderContainerView;                            //@synthesize borderContainerView=_borderContainerView - In the implementation block
-(SXComponentView *)componentView;
-(SXComponentStyle *)componentStyle;
-(void)applyComponentStyle;
-(void)componentVisiblityStateDidChange:(long long)arg1 ;
-(id)initWithComponentView:(id)arg1 componentStyle:(id)arg2 ;
-(void)applyFill:(id)arg1 ;
-(id)viewForFill:(id)arg1 ;
-(id)videoPlayerViewForFill:(id)arg1 ;
-(id)imageViewForFill:(id)arg1 ;
-(id)gradientViewForFill:(id)arg1 ;
-(SXImageFillView *)imageFillView;
-(void)setImageFillView:(SXImageFillView *)arg1 ;
-(UIView *)fillClippingView;
-(void)drawShadow:(id)arg1 ;
-(void)applyVideoFill:(id)arg1 ;
-(UIView *)borderContainerView;
-(void)setBorderContainerView:(UIView *)arg1 ;
-(void)setFillClippingView:(UIView *)arg1 ;
-(void)drawBorder:(id)arg1 ;
-(void)prepare;
-(SXVideoPlayerView *)playerView;
-(void)setPlayerView:(SXVideoPlayerView *)arg1 ;
-(void)setGradientView:(SXGradientView *)arg1 ;
-(SXGradientView *)gradientView;
@end

