/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIView.h>
#import <Silex/SXTextCanvasRenderSource.h>
#import <Silex/SXTransitionDataSource.h>

@class SXComponent, SXComponentLayout, SXContext, SXFillView, SXColumnLayout, SXLayoutController, SXComponentStyleRenderer, SXComponentStyle, NSString;

@interface SXComponentView : UIView <SXTextCanvasRenderSource, SXTransitionDataSource> {

	BOOL _hasRenderedContents;
	SXComponent* _component;
	SXComponentLayout* _componentLayout;
	SXContext* _context;
	long long _visibilityState;
	SXFillView* _fillView;
	SXColumnLayout* _columnLayout;
	SXLayoutController* _layoutController;
	SXComponentStyleRenderer* _styleRenderer;
	SXComponentStyle* _componentStyle;
	CGPoint _absolutePosition;
	CGRect _contentFrame;
	CGRect _originalFrame;

}

@property (nonatomic,readonly) SXComponent * component;                                   //@synthesize component=_component - In the implementation block
@property (nonatomic,retain) SXComponentLayout * componentLayout;                         //@synthesize componentLayout=_componentLayout - In the implementation block
@property (nonatomic,__weak,readonly) SXContext * context;                                //@synthesize context=_context - In the implementation block
@property (assign,nonatomic) long long visibilityState;                                   //@synthesize visibilityState=_visibilityState - In the implementation block
@property (assign,nonatomic,__weak) SXFillView * fillView;                                //@synthesize fillView=_fillView - In the implementation block
@property (nonatomic,readonly) long long preferredFullScreenAdaptivityStyle; 
@property (nonatomic,readonly) BOOL hasRenderedContents;                                  //@synthesize hasRenderedContents=_hasRenderedContents - In the implementation block
@property (assign,nonatomic) CGRect contentFrame;                                         //@synthesize contentFrame=_contentFrame - In the implementation block
@property (assign,nonatomic) CGPoint absolutePosition;                                    //@synthesize absolutePosition=_absolutePosition - In the implementation block
@property (nonatomic,readonly) CGRect absoluteFrame; 
@property (nonatomic,retain) SXColumnLayout * columnLayout;                               //@synthesize columnLayout=_columnLayout - In the implementation block
@property (assign,nonatomic,__weak) SXLayoutController * layoutController;                //@synthesize layoutController=_layoutController - In the implementation block
@property (nonatomic,retain) SXComponentStyleRenderer * styleRenderer;                    //@synthesize styleRenderer=_styleRenderer - In the implementation block
@property (nonatomic,retain) SXComponentStyle * componentStyle;                           //@synthesize componentStyle=_componentStyle - In the implementation block
@property (assign,nonatomic) CGRect originalFrame;                                        //@synthesize originalFrame=_originalFrame - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(CGRect)transitionContentFrame;
-(id)transitionComponentView;
-(id)imageContentView;
-(CGPoint)absolutePosition;
-(void)provideInfosLayoutTo:(id)arg1 ;
-(long long)preferredFullScreenAdaptivityStyle;
-(id)snapLines;
-(BOOL)gestureShouldBegin:(id)arg1 ;
-(BOOL)hasRenderedContents;
-(CGRect)absoluteFrame;
-(void)renderContents;
-(void)presentingScrollViewDidScroll:(CGPoint)arg1 ;
-(id)layoutDescription;
-(id)layoutDescriptionReference;
-(void)setLayoutController:(SXLayoutController *)arg1 ;
-(SXColumnLayout *)columnLayout;
-(SXComponentLayout *)componentLayout;
-(CGRect)originalFrameForContentView:(id)arg1 behavior:(id)arg2 ;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 context:(id)arg3 ;
-(void)setAbsolutePosition:(CGPoint)arg1 ;
-(void)setColumnLayout:(SXColumnLayout *)arg1 ;
-(void)receivedInfo:(id)arg1 fromLayoutingPhaseWithIdentifier:(id)arg2 ;
-(void)willPresentComponent;
-(void)presentComponent;
-(void)setOriginalFrame:(CGRect)arg1 ;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(SXComponentStyleRenderer *)styleRenderer;
-(SXComponentStyle *)componentStyle;
-(id)contentViewForBehavior:(id)arg1 ;
-(void)restoreBehavior;
-(void)setComponentLayout:(SXComponentLayout *)arg1 ;
-(SXFillView *)fillView;
-(void)setFillView:(SXFillView *)arg1 ;
-(void)setStyleRenderer:(SXComponentStyleRenderer *)arg1 ;
-(void)setComponentStyle:(SXComponentStyle *)arg1 ;
-(SXLayoutController *)layoutController;
-(CGRect)contentFrame;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)dealloc;
-(NSString *)description;
-(SXContext *)context;
-(CGRect)visibleFrame;
-(id)classification;
-(void)setComponent:(SXComponent *)arg1 ;
-(SXComponent *)component;
-(void)setVisibilityState:(long long)arg1 ;
-(long long)visibilityState;
-(void)setContentFrame:(CGRect)arg1 ;
-(void)discardContents;
-(CGRect)originalFrame;
@end

