/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXJSONObject.h>

@class SXFill, UIColor, SXShadow, SXBorder;

@interface SXComponentStyle : SXJSONObject

@property (nonatomic,readonly) SXFill * fill; 
@property (nonatomic,readonly) UIColor * backgroundColor; 
@property (nonatomic,readonly) UIEdgeInsets margin; 
@property (nonatomic,readonly) SXShadow * shadow; 
@property (nonatomic,readonly) SXBorder * border; 
@property (nonatomic,readonly) double opacity; 
@property (nonatomic,readonly) double cornerRadius; 
@property (nonatomic,readonly) UIColor * fullscreenBackgroundColor; 
-(UIColor *)fullscreenBackgroundColor;
-(double)cornerRadius;
-(double)opacity;
-(SXBorder *)border;
-(SXShadow *)shadow;
-(UIEdgeInsets)margin;
-(UIColor *)backgroundColor;
-(SXFill *)fill;
-(id)fillWithValue:(id)arg1 withType:(int)arg2 ;
@end

