/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Silex/Silex-Structs.h>
@class NSMutableArray, NSArray;

@interface SXColumnStack : NSObject {

	NSMutableArray* _columnStack;
	long long _numberOfColumns;

}

@property (nonatomic,readonly) NSArray * stack; 
@property (nonatomic,retain) NSMutableArray * columnStack;              //@synthesize columnStack=_columnStack - In the implementation block
@property (assign,nonatomic) long long numberOfColumns;                 //@synthesize numberOfColumns=_numberOfColumns - In the implementation block
-(id)initWithNumberOfColumns:(long long)arg1 ;
-(NSMutableArray *)columnStack;
-(id)stackComponentForComponent:(id)arg1 ;
-(id)componentsInColumnRange:(NSRange)arg1 ;
-(id)componentsBeforeComponent:(id)arg1 onlyFirstComponents:(BOOL)arg2 ;
-(id)componentsAfterComponent:(id)arg1 onlyFirstComponents:(BOOL)arg2 ;
-(id)lastComponentsInColumnRange:(NSRange)arg1 ;
-(void)addStackComponent:(id)arg1 toColumnRange:(NSRange)arg2 ;
-(void)setColumnStack:(NSMutableArray *)arg1 ;
-(NSArray *)stack;
-(id)init;
-(id)description;
-(long long)numberOfColumns;
-(void)setNumberOfColumns:(long long)arg1 ;
@end

