/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Silex/Silex-Structs.h>
@class SXComponent, SXComponentLayout, SXComponentStyle, SXContext, SXColumnLayout, NSMutableDictionary;

@interface SXComponentSizer : NSObject {

	SXComponent* _component;
	SXComponentLayout* _componentLayout;
	SXComponentStyle* _componentStyle;
	SXContext* _context;
	SXColumnLayout* _columnLayout;
	NSMutableDictionary* _infoForRendering;
	CGSize _suggestedSize;

}

@property (nonatomic,readonly) SXComponent * component;                             //@synthesize component=_component - In the implementation block
@property (nonatomic,readonly) SXComponentLayout * componentLayout;                 //@synthesize componentLayout=_componentLayout - In the implementation block
@property (nonatomic,readonly) SXComponentStyle * componentStyle;                   //@synthesize componentStyle=_componentStyle - In the implementation block
@property (nonatomic,readonly) SXContext * context;                                 //@synthesize context=_context - In the implementation block
@property (nonatomic,readonly) SXColumnLayout * columnLayout;                       //@synthesize columnLayout=_columnLayout - In the implementation block
@property (assign,nonatomic) CGSize suggestedSize;                                  //@synthesize suggestedSize=_suggestedSize - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * infoForRendering;              //@synthesize infoForRendering=_infoForRendering - In the implementation block
-(double)calculateHeightForWidth:(double)arg1 ;
-(SXColumnLayout *)columnLayout;
-(SXComponentLayout *)componentLayout;
-(CGSize)suggestedSize;
-(BOOL)allowComponentIntersection;
-(void)saveInfo:(id)arg1 forRenderingPhaseWithIdentifier:(id)arg2 ;
-(long long)minimumColumnLength;
-(NSRange)overrideColumnLayoutForColumnRange:(NSRange)arg1 ;
-(unsigned long long)shouldIgnoreMargins;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 componentStyle:(id)arg3 context:(id)arg4 columnLayout:(id)arg5 ;
-(SXComponentStyle *)componentStyle;
-(UIEdgeInsets)contentInsetsForSize:(CGSize)arg1 ;
-(void)setSuggestedSize:(CGSize)arg1 ;
-(CGRect)contentFrameForSize:(CGSize)arg1 contentInsets:(UIEdgeInsets)arg2 ;
-(NSMutableDictionary *)infoForRendering;
-(SXContext *)context;
-(SXComponent *)component;
@end

