/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SXDocumentStyle, SXContext, SXScrollView, SXGradientView, SXImageFillView, SXVideoPlayerView;

@interface SXDocumentStyleRenderer : NSObject {

	SXDocumentStyle* _documentStyle;
	SXContext* _context;
	SXScrollView* _scrollView;
	SXGradientView* _gradientView;
	SXImageFillView* _imageFillView;
	SXVideoPlayerView* _playerView;

}

@property (nonatomic,__weak,readonly) SXContext * context;                    //@synthesize context=_context - In the implementation block
@property (nonatomic,__weak,readonly) SXScrollView * scrollView;              //@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,readonly) SXDocumentStyle * documentStyle;               //@synthesize documentStyle=_documentStyle - In the implementation block
@property (nonatomic,retain) SXGradientView * gradientView;                   //@synthesize gradientView=_gradientView - In the implementation block
@property (nonatomic,retain) SXImageFillView * imageFillView;                 //@synthesize imageFillView=_imageFillView - In the implementation block
@property (nonatomic,retain) SXVideoPlayerView * playerView;                  //@synthesize playerView=_playerView - In the implementation block
-(id)initWithScrollView:(id)arg1 context:(id)arg2 ;
-(void)applyDocumentStyle;
-(SXDocumentStyle *)documentStyle;
-(void)applyFill:(id)arg1 ;
-(id)viewForFill:(id)arg1 ;
-(id)videoPlayerViewForFill:(id)arg1 ;
-(id)imageViewForFill:(id)arg1 ;
-(id)gradientViewForFill:(id)arg1 ;
-(SXImageFillView *)imageFillView;
-(void)setImageFillView:(SXImageFillView *)arg1 ;
-(SXScrollView *)scrollView;
-(SXContext *)context;
-(SXVideoPlayerView *)playerView;
-(void)setPlayerView:(SXVideoPlayerView *)arg1 ;
-(void)setGradientView:(SXGradientView *)arg1 ;
-(SXGradientView *)gradientView;
@end

