/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Silex/Silex-Structs.h>
@class NSString, SXMargin;

@interface SXDynamicLayout : NSObject {

	NSString* _identifier;
	unsigned long long _ignoreDocumentMargin;
	SXMargin* _margin;
	NSRange _columnRange;

}

@property (nonatomic,readonly) NSString * identifier;                                //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) NSRange columnRange;                                  //@synthesize columnRange=_columnRange - In the implementation block
@property (nonatomic,readonly) unsigned long long ignoreDocumentMargin;              //@synthesize ignoreDocumentMargin=_ignoreDocumentMargin - In the implementation block
@property (nonatomic,readonly) SXMargin * margin;                                    //@synthesize margin=_margin - In the implementation block
-(NSRange)columnRange;
-(id)initWithColumnRange:(NSRange)arg1 margin:(id)arg2 andIgnoreDocumentMargin:(unsigned long long)arg3 ;
-(unsigned long long)ignoreDocumentMargin;
-(NSString *)identifier;
-(SXMargin *)margin;
@end

