/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentView.h>
#import <libobjc.A.dylib/WKNavigationDelegate.h>
#import <libobjc.A.dylib/WKNavigationDelegatePrivate.h>

@class WKWebView, SXMediaExposureEvent, NSString;

@interface SXEmbedVideoComponentView : SXComponentView <WKNavigationDelegate, WKNavigationDelegatePrivate> {

	BOOL _webViewIsLoaded;
	WKWebView* _webView;
	SXMediaExposureEvent* _activeExposureEvent;

}

@property (nonatomic,retain) WKWebView * webView;                                     //@synthesize webView=_webView - In the implementation block
@property (assign,nonatomic) BOOL webViewIsLoaded;                                    //@synthesize webViewIsLoaded=_webViewIsLoaded - In the implementation block
@property (nonatomic,retain) SXMediaExposureEvent * activeExposureEvent;              //@synthesize activeExposureEvent=_activeExposureEvent - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedConfiguration;
-(CGRect)transitionContentFrame;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 context:(id)arg3 ;
-(void)presentComponent;
-(void)finishMediaExposureEvent;
-(void)createMediaExposureEventIfLoadedAndVisible;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(SXMediaExposureEvent *)activeExposureEvent;
-(void)setActiveExposureEvent:(SXMediaExposureEvent *)arg1 ;
-(BOOL)webViewIsLoaded;
-(void)setWebViewIsLoaded:(BOOL)arg1 ;
-(void)updateWebViewToWidth:(double)arg1 ;
-(void)initializeWebViewWithURL:(id)arg1 ;
-(void)willMoveToWindow:(id)arg1 ;
-(WKWebView *)webView;
-(void)setWebView:(WKWebView *)arg1 ;
-(CGRect)visibleFrame;
-(void)handleError:(id)arg1 ;
-(void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3 ;
-(void)webView:(id)arg1 didFinishNavigation:(id)arg2 ;
-(void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3 ;
-(void)_webViewWebProcessDidCrash:(id)arg1 ;
@end

