/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXActionHandler.h>
#import <libobjc.A.dylib/EKEventEditViewDelegate.h>

@class UIAlertAction, NSString;

@interface SXEventActionHandler : SXActionHandler <EKEventEditViewDelegate> {

	UIAlertAction* _createEventAction;
	UIAlertAction* _showInCalendarAction;
	UIAlertAction* _copyAction;

}

@property (nonatomic,readonly) UIAlertAction * createEventAction;                 //@synthesize createEventAction=_createEventAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * showInCalendarAction;              //@synthesize showInCalendarAction=_showInCalendarAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * copyAction;                        //@synthesize copyAction=_copyAction - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(UIAlertAction *)copyAction;
-(id)alertActions;
-(UIAlertAction *)createEventAction;
-(UIAlertAction *)showInCalendarAction;
-(void)createEvent;
-(BOOL)canShowInCalendar;
-(void)showInCalendar;
-(id)title;
-(id)message;
-(void)copyToPasteboard;
-(void)eventEditViewController:(id)arg1 didCompleteWithAction:(long long)arg2 ;
@end

