/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIView.h>

@class SXFill, UIView;

@interface SXFillView : UIView {

	SXFill* _fill;
	UIView* _clippingView;
	CGRect _originalFrame;

}

@property (nonatomic,readonly) SXFill * fill;                           //@synthesize fill=_fill - In the implementation block
@property (assign,nonatomic,__weak) UIView * clippingView;              //@synthesize clippingView=_clippingView - In the implementation block
@property (nonatomic,readonly) CGRect fillFrame; 
@property (assign,nonatomic) CGRect originalFrame;                      //@synthesize originalFrame=_originalFrame - In the implementation block
-(id)initWithFill:(id)arg1 ;
-(CGRect)fillFrame;
-(UIView *)clippingView;
-(void)setClippingView:(UIView *)arg1 ;
-(void)setOriginalFrame:(CGRect)arg1 ;
-(SXFill *)fill;
-(CGRect)originalFrame;
@end

