/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXTextSourceDataSource.h>

@protocol SXTextSourceDataSource;
@class NSString, SXCaption;

@interface SXFullScreenCaption : NSObject <SXTextSourceDataSource> {

	NSString* _text;
	SXCaption* _caption;
	id<SXTextSourceDataSource> _textSourceDataSource;

}

@property (nonatomic,readonly) NSString * text;                                                     //@synthesize text=_text - In the implementation block
@property (nonatomic,readonly) SXCaption * caption;                                                 //@synthesize caption=_caption - In the implementation block
@property (nonatomic,__weak,readonly) id<SXTextSourceDataSource> textSourceDataSource;              //@synthesize textSourceDataSource=_textSourceDataSource - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)documentController;
-(id)textRules;
-(id<SXTextSourceDataSource>)textSourceDataSource;
-(id)textResizer;
-(id)additions;
-(id)inlineTextStyles;
-(id)initWithText:(id)arg1 textSourceDataSource:(id)arg2 ;
-(id)initWithCaption:(id)arg1 textSourceDataSource:(id)arg2 ;
-(NSString *)text;
-(id)textStyle;
-(SXCaption *)caption;
@end

