/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIView.h>
#import <Silex/SXAutoSizedCanvasControllerDelegate.h>
#import <Silex/SXStandaloneTextLayoutDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol SXFullScreenCaptionViewDelegate;
@class SXFullScreenCaption, UITapGestureRecognizer, SXAutoSizedCanvasController, SXTextTangierDocumentRoot, SXStandaloneTextInfo, SXStandaloneTextLayout, UIVisualEffectView, UIScrollView, UISwipeGestureRecognizer, SXTextSource, SXStandaloneTextStorage, NSString;

@interface SXFullScreenCaptionView : UIView <SXAutoSizedCanvasControllerDelegate, SXStandaloneTextLayoutDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate> {

	int _expansionMode;
	id<SXFullScreenCaptionViewDelegate> _delegate;
	SXFullScreenCaption* _caption;
	unsigned long long _viewIndex;
	UITapGestureRecognizer* _tapGestureRecognizer;
	SXAutoSizedCanvasController* _autoSizeCanvasController;
	SXTextTangierDocumentRoot* _documentRoot;
	SXStandaloneTextInfo* _captionInfo;
	SXStandaloneTextLayout* _captionLayout;
	UIVisualEffectView* _backgroundView;
	UIScrollView* _scrollView;
	UISwipeGestureRecognizer* _swipeGestureRecognizer;
	SXTextSource* _textSource;
	SXStandaloneTextStorage* _textStorage;
	CGSize _fullSize;
	CGRect _temporaryLayoutRect;

}

@property (assign,nonatomic,__weak) id<SXFullScreenCaptionViewDelegate> delegate;                 //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) SXFullScreenCaption * caption;                                     //@synthesize caption=_caption - In the implementation block
@property (nonatomic,readonly) unsigned long long viewIndex;                                      //@synthesize viewIndex=_viewIndex - In the implementation block
@property (nonatomic,readonly) int expansionMode;                                                 //@synthesize expansionMode=_expansionMode - In the implementation block
@property (nonatomic,readonly) BOOL expanded; 
@property (nonatomic,retain) UITapGestureRecognizer * tapGestureRecognizer;                       //@synthesize tapGestureRecognizer=_tapGestureRecognizer - In the implementation block
@property (nonatomic,retain) SXAutoSizedCanvasController * autoSizeCanvasController;              //@synthesize autoSizeCanvasController=_autoSizeCanvasController - In the implementation block
@property (nonatomic,retain) SXTextTangierDocumentRoot * documentRoot;                            //@synthesize documentRoot=_documentRoot - In the implementation block
@property (nonatomic,retain) SXStandaloneTextInfo * captionInfo;                                  //@synthesize captionInfo=_captionInfo - In the implementation block
@property (nonatomic,retain) SXStandaloneTextLayout * captionLayout;                              //@synthesize captionLayout=_captionLayout - In the implementation block
@property (assign,nonatomic) CGRect temporaryLayoutRect;                                          //@synthesize temporaryLayoutRect=_temporaryLayoutRect - In the implementation block
@property (assign,nonatomic) CGSize fullSize;                                                     //@synthesize fullSize=_fullSize - In the implementation block
@property (nonatomic,retain) UIVisualEffectView * backgroundView;                                 //@synthesize backgroundView=_backgroundView - In the implementation block
@property (nonatomic,retain) UIScrollView * scrollView;                                           //@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,retain) UISwipeGestureRecognizer * swipeGestureRecognizer;                   //@synthesize swipeGestureRecognizer=_swipeGestureRecognizer - In the implementation block
@property (nonatomic,retain) SXTextSource * textSource;                                           //@synthesize textSource=_textSource - In the implementation block
@property (nonatomic,retain) SXStandaloneTextStorage * textStorage;                               //@synthesize textStorage=_textStorage - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)_applyStyle:(id)arg1 toStorage:(id)arg2 ;
+(id)_overridePropertiesWithComponentStyle:(id)arg1 storage:(id)arg2 ;
-(void)createBackgroundView;
-(void)createScrollView;
-(void)setupGestureRecognizers;
-(void)initializeTangier;
-(int)expansionMode;
-(void)renderCaptionInTangier;
-(void)updateFrameAnimated:(BOOL)arg1 ;
-(SXAutoSizedCanvasController *)autoSizeCanvasController;
-(void)setExpansionMode:(int)arg1 animated:(BOOL)arg2 ;
-(CGRect)frameWithSize:(CGSize)arg1 forExpansionMode:(int)arg2 ;
-(void)setTemporaryLayoutRect:(CGRect)arg1 ;
-(CGRect)determineFrameInSuperview:(id)arg1 ;
-(SXStandaloneTextLayout *)captionLayout;
-(void)setTextSource:(SXTextSource *)arg1 ;
-(SXTextSource *)textSource;
-(void)setCaptionInfo:(SXStandaloneTextInfo *)arg1 ;
-(SXStandaloneTextInfo *)captionInfo;
-(void)setCaptionLayout:(SXStandaloneTextLayout *)arg1 ;
-(CGRect)temporaryLayoutRect;
-(void)handleSwipeGestureRecognizer:(id)arg1 ;
-(UISwipeGestureRecognizer *)swipeGestureRecognizer;
-(void)handleTapGestureRecognizer:(id)arg1 ;
-(BOOL)forceFullExpandsionMode;
-(double)marginForTextLayout:(id)arg1 ;
-(double)widthForTextLayout:(id)arg1 ;
-(CGPoint)positionForTextLayout:(id)arg1 ;
-(void)updateWithCaption:(id)arg1 forViewIndex:(unsigned long long)arg2 animated:(BOOL)arg3 ;
-(unsigned long long)viewIndex;
-(void)setAutoSizeCanvasController:(SXAutoSizedCanvasController *)arg1 ;
-(void)setFullSize:(CGSize)arg1 ;
-(void)setSwipeGestureRecognizer:(UISwipeGestureRecognizer *)arg1 ;
-(void)setDelegate:(id<SXFullScreenCaptionViewDelegate>)arg1 ;
-(void)dealloc;
-(void)setNeedsLayout;
-(id)init;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)scrollViewDidScroll:(id)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<SXFullScreenCaptionViewDelegate>)delegate;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(UIScrollView *)scrollView;
-(void)didMoveToSuperview;
-(void)setBackgroundView:(UIVisualEffectView *)arg1 ;
-(UIVisualEffectView *)backgroundView;
-(SXStandaloneTextStorage *)textStorage;
-(BOOL)expanded;
-(void)setTextStorage:(SXStandaloneTextStorage *)arg1 ;
-(SXFullScreenCaption *)caption;
-(UITapGestureRecognizer *)tapGestureRecognizer;
-(void)setTapGestureRecognizer:(UITapGestureRecognizer *)arg1 ;
-(CGSize)fullSize;
-(SXTextTangierDocumentRoot *)documentRoot;
-(void)setDocumentRoot:(SXTextTangierDocumentRoot *)arg1 ;
@end

