/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXHeadingComponentClassification.h>

@interface SXHeading6ComponentClassification : SXHeadingComponentClassification
+(id)roleString;
+(int)role;
+(id)typeString;
-(id)accessibilityContextualLabel;
-(id)accessibilityCustomRotorMembership;
@end

