/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Silex/Silex-Structs.h>
@class NSDictionary, SXDocumentController, SXColumnLayout, NSMutableDictionary;

@interface SXImageController : NSObject {

	NSDictionary* _imageResourcesGroupedByImageIdentifier;
	NSDictionary* _image2ResourcesGroupedByImageIdentifier;
	SXDocumentController* _documentController;
	SXColumnLayout* _columnLayout;
	NSMutableDictionary* _optimalImageResources;
	CGSize _viewportSize;

}

@property (nonatomic,__weak,readonly) SXDocumentController * documentController;                    //@synthesize documentController=_documentController - In the implementation block
@property (nonatomic,readonly) SXColumnLayout * columnLayout;                                       //@synthesize columnLayout=_columnLayout - In the implementation block
@property (nonatomic,readonly) CGSize viewportSize;                                                 //@synthesize viewportSize=_viewportSize - In the implementation block
@property (nonatomic,readonly) NSDictionary * imageResourcesGroupedByImageIdentifier;               //@synthesize imageResourcesGroupedByImageIdentifier=_imageResourcesGroupedByImageIdentifier - In the implementation block
@property (nonatomic,readonly) NSDictionary * image2ResourcesGroupedByImageIdentifier;              //@synthesize image2ResourcesGroupedByImageIdentifier=_image2ResourcesGroupedByImageIdentifier - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * optimalImageResources;                         //@synthesize optimalImageResources=_optimalImageResources - In the implementation block
-(SXDocumentController *)documentController;
-(id)imageResourceForIdentifier:(id)arg1 ;
-(SXColumnLayout *)columnLayout;
-(id)initWithDocumentController:(id)arg1 ;
-(id)allImageResources;
-(void)determineOptimalImagesForComponents:(id)arg1 ;
-(id)imageResourcesForComponent:(id)arg1 ;
-(NSMutableDictionary *)optimalImageResources;
-(id)imageResourcesForComponentStyle:(id)arg1 ;
-(id)imageResourceForImageComponent:(id)arg1 ;
-(id)imageResourceForScalableImageComponent:(id)arg1 ;
-(id)imageResourceForVideoComponent:(id)arg1 ;
-(id)imageResourceForAudioComponent:(id)arg1 ;
-(id)imageResourcesForGalleryComponent:(id)arg1 ;
-(CGSize)sizeConstraintForComponent:(id)arg1 ;
-(id)imageResourceForImageIdentifier:(id)arg1 constrainedToSize:(CGSize)arg2 allowsUpscaling:(BOOL)arg3 ;
-(id)imageResourceForGalleryItem:(id)arg1 ;
-(id)imageResourceForImageFill:(id)arg1 ;
-(id)imageResourceForVideoFill:(id)arg1 ;
-(id)imageResourcesForImageIdentifier:(id)arg1 ;
-(id)largestImageResourceForImageIdentifier:(id)arg1 ;
-(id)taggedEquivalentOfImageResource:(id)arg1 ;
-(id)Image2ResourcesForImageIdentifier:(id)arg1 ;
-(NSDictionary *)imageResourcesGroupedByImageIdentifier;
-(NSDictionary *)image2ResourcesGroupedByImageIdentifier;
-(CGSize)viewportSize;
@end

