/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SXImageViewDelegate <NSObject>
@optional
-(void)imageView:(id)arg1 didLoadImage:(id)arg2 ofQuality:(int)arg3;
-(void)imageView:(id)arg1 didLoadAnimatedImage:(id)arg2;

@end

