/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Foundation/NSOperation.h>
#import <Silex/SXLayouterDelegate.h>

@class SXLayoutDataProvider, NSString, SXLayoutBlueprint;

@interface SXLayoutOperation : NSOperation <SXLayouterDelegate> {

	BOOL _executing;
	BOOL _finished;
	double _limitingHeight;
	SXLayoutDataProvider* _layoutDataProvider;
	NSString* _contentSizeCategory;
	SXLayoutBlueprint* _layoutBlueprint;
	CGSize _viewportSize;

}

@property (nonatomic,readonly) CGSize viewportSize;                                    //@synthesize viewportSize=_viewportSize - In the implementation block
@property (nonatomic,readonly) double limitingHeight;                                  //@synthesize limitingHeight=_limitingHeight - In the implementation block
@property (nonatomic,readonly) SXLayoutDataProvider * layoutDataProvider;              //@synthesize layoutDataProvider=_layoutDataProvider - In the implementation block
@property (nonatomic,readonly) NSString * contentSizeCategory;                         //@synthesize contentSizeCategory=_contentSizeCategory - In the implementation block
@property (nonatomic,retain) SXLayoutBlueprint * layoutBlueprint;                      //@synthesize layoutBlueprint=_layoutBlueprint - In the implementation block
@property (assign) BOOL executing;                                                     //@synthesize executing=_executing - In the implementation block
@property (assign) BOOL finished;                                                      //@synthesize finished=_finished - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(SXLayoutDataProvider *)layoutDataProvider;
-(SXLayoutBlueprint *)layoutBlueprint;
-(void)setLayoutBlueprint:(SXLayoutBlueprint *)arg1 ;
-(id)initWithViewportSize:(CGSize)arg1 limitingHeight:(double)arg2 contentSizeCategory:(id)arg3 andLayoutDataProvider:(id)arg4 ;
-(void)doStartBookKeeping;
-(void)startLayoutWork;
-(void)doFinishBookKeeping;
-(BOOL)isValidLayoutBlueprint:(id)arg1 viewportSize:(CGSize)arg2 contentSizeCategory:(id)arg3 ;
-(BOOL)layoutBlueprint:(id)arg1 isFinishedForLayoutDataProvider:(id)arg2 ;
-(void)doneLayoutWorkWithLayoutBlueprint:(id)arg1 ;
-(id)columnLayoutForLayout:(id)arg1 viewportSize:(CGSize)arg2 contentSizeCategory:(id)arg3 ;
-(id)createLayoutBlueprintForColumnLayout:(id)arg1 andLayoutDataProvider:(id)arg2 ;
-(void)updateLayoutBlueprint:(id)arg1 usingLayoutDataProvider:(id)arg2 ;
-(void)finalizeLayoutBlueprint:(id)arg1 startOffset:(CGPoint)arg2 ;
-(id)columnStackForLayoutBlueprint:(id)arg1 andLayoutDataProvider:(id)arg2 ;
-(double)limitingHeight;
-(void)layouter:(id)arg1 didFinishLayoutForComponent:(id)arg2 layoutBlueprint:(id)arg3 shouldContinueLayout:(BOOL*)arg4 ;
-(id)layoutBlueprint:(id)arg1 componentLayoutForComponent:(id)arg2 ;
-(BOOL)layouter:(id)arg1 allowResizingOfComponent:(id)arg2 ;
-(BOOL)isAsynchronous;
-(NSString *)contentSizeCategory;
-(void)start;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(void)setFinished:(BOOL)arg1 ;
-(BOOL)finished;
-(CGSize)viewportSize;
-(BOOL)executing;
-(void)setExecuting:(BOOL)arg1 ;
@end

