/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXAction.h>

@class NSURL;

@interface SXLinkAction : SXAction {

	NSURL* _URL;

}

@property (nonatomic,readonly) NSURL * URL;              //@synthesize URL=_URL - In the implementation block
-(Class)handlerClass;
-(id)initWithURL:(id)arg1 addition:(id)arg2 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSURL *)URL;
-(id)initWithAddition:(id)arg1 ;
@end

