/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXActionHandler.h>

@class UIAlertAction;

@interface SXLongPressLinkActionHandler : SXActionHandler {

	UIAlertAction* _openAction;
	UIAlertAction* _openInSafariAction;
	UIAlertAction* _copyAction;

}

@property (nonatomic,readonly) UIAlertAction * openAction;                      //@synthesize openAction=_openAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * openInSafariAction;              //@synthesize openInSafariAction=_openInSafariAction - In the implementation block
@property (nonatomic,readonly) UIAlertAction * copyAction;                      //@synthesize copyAction=_copyAction - In the implementation block
-(UIAlertAction *)copyAction;
-(id)alertActions;
-(UIAlertAction *)openAction;
-(UIAlertAction *)openInSafariAction;
-(void)openLinkInApp;
-(void)openLinkInSafari;
-(id)title;
-(id)message;
-(void)copyToPasteboard;
@end

