/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXJSONObject.h>

@class NSString, SXJSONDictionary;

@interface SXMetaData : SXJSONObject

@property (nonatomic,readonly) BOOL transparentToolbar; 
@property (nonatomic,readonly) NSString * canonicalURL; 
@property (nonatomic,readonly) NSString * thumbnailImageIdentifier; 
@property (nonatomic,readonly) SXJSONDictionary * campaignData; 
-(SXJSONDictionary *)campaignData;
-(NSString *)thumbnailImageIdentifier;
-(NSString *)canonicalURL;
-(BOOL)transparentToolbar;
@end

