/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXAnalyticsEvent.h>

@class NSString, NSArray;

@interface SXMediaViewEvent : SXAnalyticsEvent {

	unsigned long long _mediaType;
	NSString* _mediaId;
	unsigned long long _galleryType;
	unsigned long long _galleryImageCount;
	NSArray* _galleryImageIds;

}

@property (assign,nonatomic) unsigned long long mediaType;                      //@synthesize mediaType=_mediaType - In the implementation block
@property (nonatomic,retain) NSString * mediaId;                                //@synthesize mediaId=_mediaId - In the implementation block
@property (assign,nonatomic) unsigned long long galleryType;                    //@synthesize galleryType=_galleryType - In the implementation block
@property (assign,nonatomic) unsigned long long galleryImageCount;              //@synthesize galleryImageCount=_galleryImageCount - In the implementation block
@property (nonatomic,retain) NSArray * galleryImageIds;                         //@synthesize galleryImageIds=_galleryImageIds - In the implementation block
-(void)setMediaId:(NSString *)arg1 ;
-(void)setGalleryImageCount:(unsigned long long)arg1 ;
-(unsigned long long)galleryType;
-(void)setGalleryType:(unsigned long long)arg1 ;
-(NSString *)mediaId;
-(unsigned long long)galleryImageCount;
-(NSArray *)galleryImageIds;
-(void)setGalleryImageIds:(NSArray *)arg1 ;
-(unsigned long long)mediaType;
-(void)setMediaType:(unsigned long long)arg1 ;
@end

