/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentBehaviorHandler.h>

@class UIView, UIInterpolatingMotionEffect;

@interface SXMotionImageComponentBehaviorHandler : SXComponentBehaviorHandler {

	BOOL _motionContentSuperViewWasClipped;
	BOOL _isRotating;
	UIView* _motionContentView;
	UIInterpolatingMotionEffect* _xMotionEffect;
	UIInterpolatingMotionEffect* _yMotionEffect;

}

@property (nonatomic,retain) UIView * motionContentView;                               //@synthesize motionContentView=_motionContentView - In the implementation block
@property (assign,nonatomic) BOOL motionContentSuperViewWasClipped;                    //@synthesize motionContentSuperViewWasClipped=_motionContentSuperViewWasClipped - In the implementation block
@property (nonatomic,readonly) BOOL motionDetectionIsPaused; 
@property (nonatomic,readonly) BOOL isRotating;                                        //@synthesize isRotating=_isRotating - In the implementation block
@property (nonatomic,retain) UIInterpolatingMotionEffect * xMotionEffect;              //@synthesize xMotionEffect=_xMotionEffect - In the implementation block
@property (nonatomic,retain) UIInterpolatingMotionEffect * yMotionEffect;              //@synthesize yMotionEffect=_yMotionEffect - In the implementation block
-(id)initWithComponentView:(id)arg1 withBehavior:(id)arg2 ;
-(void)updateWithBehaviorController:(id)arg1 ;
-(void)destroyWithBehaviorController:(id)arg1 ;
-(void)hostingViewWillChangeSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)setupMotionDetection;
-(BOOL)motionDetectionIsPaused;
-(void)resumeMotionDetection;
-(void)pauseMotionDetection;
-(void)destroyMotionDetection;
-(UIView *)motionContentView;
-(void)setMotionContentView:(UIView *)arg1 ;
-(void)setMotionContentSuperViewWasClipped:(BOOL)arg1 ;
-(void)setXMotionEffect:(UIInterpolatingMotionEffect *)arg1 ;
-(UIInterpolatingMotionEffect *)xMotionEffect;
-(void)setYMotionEffect:(UIInterpolatingMotionEffect *)arg1 ;
-(UIInterpolatingMotionEffect *)yMotionEffect;
-(BOOL)motionContentSuperViewWasClipped;
-(BOOL)isRotating;
@end

