/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXMosaicGalleryGroupLayout.h>

@interface SXMosaicGalleryVerticalLivingRoomLayout : SXMosaicGalleryGroupLayout {

	double _largeItemHeight;
	double _smallItemHeight;

}

@property (nonatomic,readonly) double largeItemHeight;              //@synthesize largeItemHeight=_largeItemHeight - In the implementation block
@property (nonatomic,readonly) double smallItemHeight;              //@synthesize smallItemHeight=_smallItemHeight - In the implementation block
-(NSRange)columnRangeForItem:(id)arg1 ;
-(double)calculateHeight;
-(id)calculateFrames;
-(id)initWithCluster:(id)arg1 numberOfColumns:(unsigned long long)arg2 columnLayout:(id)arg3 ;
-(double)largeItemHeight;
-(double)smallItemHeight;
@end

