/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXGalleryComponentView.h>
#import <Silex/SXMosaicGalleryLayouterDataSource.h>
#import <Silex/SXFullScreenCanvasShowable.h>
#import <Silex/SXImageViewDelegate.h>
#import <Silex/SXTextSourceDataSource.h>

@class SXFullScreenCanvasController, UIView, NSMutableArray, SXMediaExposureEvent, SXMediaViewEvent, SXMosaicGalleryLayouter, NSString;

@interface SXMosaicGalleryComponentView : SXGalleryComponentView <SXMosaicGalleryLayouterDataSource, SXFullScreenCanvasShowable, SXImageViewDelegate, SXTextSourceDataSource> {

	BOOL _loadedAtleastOneImage;
	SXFullScreenCanvasController* _fullScreenCanvasController;
	UIView* _galleryView;
	NSMutableArray* _imageViews;
	NSMutableArray* _visibleImageViews;
	SXMediaExposureEvent* _activeExposureEvent;
	SXMediaViewEvent* _activeViewEvent;
	SXMosaicGalleryLayouter* _galleryLayouter;

}

@property (nonatomic,readonly) SXFullScreenCanvasController * fullScreenCanvasController;              //@synthesize fullScreenCanvasController=_fullScreenCanvasController - In the implementation block
@property (nonatomic,retain) UIView * galleryView;                                                     //@synthesize galleryView=_galleryView - In the implementation block
@property (nonatomic,readonly) NSMutableArray * imageViews;                                            //@synthesize imageViews=_imageViews - In the implementation block
@property (nonatomic,readonly) NSMutableArray * visibleImageViews;                                     //@synthesize visibleImageViews=_visibleImageViews - In the implementation block
@property (nonatomic,retain) SXMediaExposureEvent * activeExposureEvent;                               //@synthesize activeExposureEvent=_activeExposureEvent - In the implementation block
@property (nonatomic,retain) SXMediaViewEvent * activeViewEvent;                                       //@synthesize activeViewEvent=_activeViewEvent - In the implementation block
@property (assign,nonatomic) BOOL loadedAtleastOneImage;                                               //@synthesize loadedAtleastOneImage=_loadedAtleastOneImage - In the implementation block
@property (nonatomic,retain) SXMosaicGalleryLayouter * galleryLayouter;                                //@synthesize galleryLayouter=_galleryLayouter - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)documentController;
-(id)textRules;
-(void)renderContents;
-(void)presentingScrollViewDidScroll:(CGPoint)arg1 ;
-(id)imageViewForLocation:(CGPoint)arg1 ;
-(void)forceImageViewFullscreen:(id)arg1 ;
-(void)imageView:(id)arg1 didLoadImage:(id)arg2 ofQuality:(int)arg3 ;
-(void)imageView:(id)arg1 didLoadAnimatedImage:(id)arg2 ;
-(id)initWithComponent:(id)arg1 componentLayout:(id)arg2 context:(id)arg3 ;
-(void)receivedInfo:(id)arg1 fromLayoutingPhaseWithIdentifier:(id)arg2 ;
-(void)presentComponent;
-(id)textResizer;
-(id)additions;
-(id)inlineTextStyles;
-(void)finishMediaExposureEvent;
-(void)finishMediaViewEvent;
-(SXMosaicGalleryLayouter *)galleryLayouter;
-(SXFullScreenCanvasController *)fullScreenCanvasController;
-(CGRect)drawableRectForContentOffset:(CGPoint)arg1 ;
-(void)renderContentsInRect:(CGRect)arg1 ;
-(NSMutableArray *)visibleImageViews;
-(void)setGalleryLayouter:(SXMosaicGalleryLayouter *)arg1 ;
-(void)setLoadedAtleastOneImage:(BOOL)arg1 ;
-(void)createMediaExposureEventIfLoadedAndVisible;
-(id)imageViewForItemAtIndex:(unsigned long long)arg1 ;
-(void)createMediaViewEvent;
-(void)didViewImageWithIdentifier:(id)arg1 ;
-(unsigned long long)numberOfItemsForGalleryLayouter:(id)arg1 ;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(SXMediaExposureEvent *)activeExposureEvent;
-(BOOL)loadedAtleastOneImage;
-(void)setActiveExposureEvent:(SXMediaExposureEvent *)arg1 ;
-(SXMediaViewEvent *)activeViewEvent;
-(void)setActiveViewEvent:(SXMediaViewEvent *)arg1 ;
-(CGSize)galleryLayouter:(id)arg1 dimensionsForItemAtIndex:(unsigned long long)arg2 ;
-(id)galleryLayouter:(id)arg1 viewForItemAtIndex:(unsigned long long)arg2 ;
-(BOOL)galleryLayouter:(id)arg1 viewIsCurrentlyFullscreenForItemAtIndex:(unsigned long long)arg2 ;
-(id)columnLayoutForGalleryLayouter:(id)arg1 ;
-(void)fullScreenCanvasController:(id)arg1 willTransitionToFullScreenAnimated:(BOOL)arg2 ;
-(void)fullScreenCanvasController:(id)arg1 didTransitionToFullScreenAnimated:(BOOL)arg2 ;
-(void)fullScreenCanvasController:(id)arg1 willTransitionFromFullScreenAnimated:(BOOL)arg2 ;
-(void)fullScreenCanvasController:(id)arg1 didTransitionFromFullScreenAnimated:(BOOL)arg2 ;
-(unsigned long long)fullScreenCanvasController:(id)arg1 numberOfViewsForShowable:(id)arg2 ;
-(void)fullScreenCanvasController:(id)arg1 shouldAddGestureView:(id)arg2 forShowable:(id)arg3 ;
-(id)fullScreenCanvasController:(id)arg1 canvasViewForShowable:(id)arg2 ;
-(unsigned long long)fullScreenCanvasController:(id)arg1 viewIndexForPoint:(CGPoint)arg2 inShowable:(id)arg3 ;
-(id)fullScreenCanvasController:(id)arg1 originalViewForShowable:(id)arg2 viewIndex:(unsigned long long)arg3 ;
-(CGRect)fullScreenCanvasController:(id)arg1 originalFrameForShowable:(id)arg2 onCanvasView:(id)arg3 viewIndex:(unsigned long long)arg4 ;
-(CGRect)fullScreenCanvasController:(id)arg1 fullScreenFrameForShowable:(id)arg2 viewIndex:(unsigned long long)arg3 withinRect:(CGRect)arg4 ;
-(void)fullScreenCanvasController:(id)arg1 showable:(id)arg2 shouldTransferToOriginalViewWithIndex:(unsigned long long)arg3 ;
-(BOOL)requestInteractivityFocusForFullScreenCanvasController:(id)arg1 ;
-(id)fullScreenCanvasController:(id)arg1 captionForShowable:(id)arg2 viewIndex:(unsigned long long)arg3 ;
-(BOOL)fullScreenCanvasController:(id)arg1 willShowShowable:(id)arg2 viewIndex:(unsigned long long)arg3 ;
-(void)fullScreenCanvasController:(id)arg1 didShowShowable:(id)arg2 viewIndex:(unsigned long long)arg3 ;
-(void)fullScreenCanvasController:(id)arg1 willHideShowable:(id)arg2 viewIndex:(unsigned long long)arg3 ;
-(void)fullScreenCanvasController:(id)arg1 didHideShowable:(id)arg2 viewIndex:(unsigned long long)arg3 ;
-(void)fullScreenCanvasController:(id)arg1 showable:(id)arg2 didShowViewWithIndex:(unsigned long long)arg3 ;
-(void)fullScreenCanvasController:(id)arg1 showable:(id)arg2 willShowViewWithIndex:(unsigned long long)arg3 ;
-(void)fullScreenCanvasController:(id)arg1 showable:(id)arg2 didHideViewWithIndex:(unsigned long long)arg3 ;
-(BOOL)fullScreenCanvasController:(id)arg1 showable:(id)arg2 gestureRecognizerShouldBegin:(id)arg3 ;
-(void)willMoveToWindow:(id)arg1 ;
-(id)textStyle;
-(void)setGalleryView:(UIView *)arg1 ;
-(UIView *)galleryView;
-(NSMutableArray *)imageViews;
-(void)discardContents;
@end

