/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXGalleryComponentSizer.h>
#import <Silex/SXMosaicGalleryLayouterDataSource.h>

@class SXMosaicGalleryLayouter, NSString;

@interface SXMosaicGalleryComponentSizer : SXGalleryComponentSizer <SXMosaicGalleryLayouterDataSource> {

	SXMosaicGalleryLayouter* _layouter;

}

@property (nonatomic,retain) SXMosaicGalleryLayouter * layouter;              //@synthesize layouter=_layouter - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(double)calculateHeightForWidth:(double)arg1 ;
-(SXMosaicGalleryLayouter *)layouter;
-(Class)componentBlueprintClass;
-(void)updateComponentBlueprint:(id)arg1 ;
-(unsigned long long)numberOfItemsForGalleryLayouter:(id)arg1 ;
-(CGSize)galleryLayouter:(id)arg1 dimensionsForItemAtIndex:(unsigned long long)arg2 ;
-(id)galleryLayouter:(id)arg1 viewForItemAtIndex:(unsigned long long)arg2 ;
-(BOOL)galleryLayouter:(id)arg1 viewIsCurrentlyFullscreenForItemAtIndex:(unsigned long long)arg2 ;
-(id)columnLayoutForGalleryLayouter:(id)arg1 ;
-(void)setLayouter:(SXMosaicGalleryLayouter *)arg1 ;
@end

