/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXComponentView.h>
#import <libobjc.A.dylib/WKUIDelegate.h>
#import <libobjc.A.dylib/WKNavigationDelegatePrivate.h>
#import <libobjc.A.dylib/WKNavigationDelegate.h>

@class WKWebView, NSString, NSTimer, UIActivityIndicatorView, SXOEmbedResponse;

@interface SXOEmbedComponentView : SXComponentView <WKUIDelegate, WKNavigationDelegatePrivate, WKNavigationDelegate> {

	BOOL _webViewIsLoaded;
	BOOL _isRetrievingOEmbedData;
	WKWebView* _webView;
	NSString* _HTML;
	double _preferredWidth;
	NSTimer* _readyTimer;
	UIActivityIndicatorView* _activityIndicatorView;
	double _webViewHeight;
	double _lastActualWidth;
	SXOEmbedResponse* _oEmbedResponse;
	CGSize _contentSizeUponLoad;
	CGSize _currentContentSize;
	CGSize _currentViewportSize;

}

@property (nonatomic,retain) WKWebView * webView;                                          //@synthesize webView=_webView - In the implementation block
@property (assign,nonatomic) BOOL webViewIsLoaded;                                         //@synthesize webViewIsLoaded=_webViewIsLoaded - In the implementation block
@property (nonatomic,readonly) NSString * HTML;                                            //@synthesize HTML=_HTML - In the implementation block
@property (assign,nonatomic) BOOL isRetrievingOEmbedData;                                  //@synthesize isRetrievingOEmbedData=_isRetrievingOEmbedData - In the implementation block
@property (assign,nonatomic) double preferredWidth;                                        //@synthesize preferredWidth=_preferredWidth - In the implementation block
@property (nonatomic,retain) NSTimer * readyTimer;                                         //@synthesize readyTimer=_readyTimer - In the implementation block
@property (assign,nonatomic) CGSize contentSizeUponLoad;                                   //@synthesize contentSizeUponLoad=_contentSizeUponLoad - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * activityIndicatorView;              //@synthesize activityIndicatorView=_activityIndicatorView - In the implementation block
@property (nonatomic,readonly) double webViewHeight;                                       //@synthesize webViewHeight=_webViewHeight - In the implementation block
@property (assign,nonatomic) double lastActualWidth;                                       //@synthesize lastActualWidth=_lastActualWidth - In the implementation block
@property (nonatomic,retain) SXOEmbedResponse * oEmbedResponse;                            //@synthesize oEmbedResponse=_oEmbedResponse - In the implementation block
@property (assign,nonatomic) CGSize currentContentSize;                                    //@synthesize currentContentSize=_currentContentSize - In the implementation block
@property (assign,nonatomic) CGSize currentViewportSize;                                   //@synthesize currentViewportSize=_currentViewportSize - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)embedWebConfiguration;
-(void)setCurrentContentSize:(CGSize)arg1 ;
-(CGSize)currentViewportSize;
-(void)willPresentComponent;
-(void)presentComponent;
-(id)additionalQueryParameters;
-(id)modifiedHTML:(id)arg1 ;
-(BOOL)shouldAllowRequestToURL:(id)arg1 ;
-(void)invalidateLayoutForNewHeight:(double)arg1 ;
-(SXOEmbedResponse *)oEmbedResponse;
-(void)updateWebView:(id)arg1 toWidth:(double)arg2 ;
-(void)didFinishLoading;
-(id)unableToLoadMessage;
-(void)visibilityStateDidChangeFromState:(long long)arg1 ;
-(NSString *)HTML;
-(BOOL)isRetrievingOEmbedData;
-(void)retrieveOEmbedData;
-(void)loadWebViewIfNeeded;
-(BOOL)webViewIsLoaded;
-(void)initializeWebViewWithHTML:(id)arg1 ;
-(void)setContentSizeUponLoad:(CGSize)arg1 ;
-(void)setWebViewIsLoaded:(BOOL)arg1 ;
-(void)setCurrentViewportSize:(CGSize)arg1 ;
-(NSTimer *)readyTimer;
-(void)setReadyTimer:(NSTimer *)arg1 ;
-(void)setIsRetrievingOEmbedData:(BOOL)arg1 ;
-(void)retrieveHTMLFromOEmbedURL:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)setOEmbedResponse:(SXOEmbedResponse *)arg1 ;
-(id)addAdditionalQueryParameters:(id)arg1 toURL:(id)arg2 ;
-(CGSize)contentSizeUponLoad;
-(double)webViewHeight;
-(double)lastActualWidth;
-(void)setLastActualWidth:(double)arg1 ;
-(WKWebView *)webView;
-(id)URL;
-(void)setWebView:(WKWebView *)arg1 ;
-(void)handleError:(id)arg1 ;
-(id)webView:(id)arg1 createWebViewWithConfiguration:(id)arg2 forNavigationAction:(id)arg3 windowFeatures:(id)arg4 ;
-(UIActivityIndicatorView *)activityIndicatorView;
-(void)setActivityIndicatorView:(UIActivityIndicatorView *)arg1 ;
-(void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(/*^block*/id)arg3 ;
-(void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3 ;
-(void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3 ;
-(void)_webViewWebProcessDidCrash:(id)arg1 ;
-(double)preferredWidth;
-(void)setPreferredWidth:(double)arg1 ;
-(CGSize)currentContentSize;
@end

