/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <Silex/SXSceneComponentAnimationHandler.h>

@class UIView, SXComponentView;

@interface SXParallaxFadeSceneAnimationHandler : SXSceneComponentAnimationHandler {

	UIView* _overlayView;
	SXComponentView* _headerComponentView;
	double _scrollDistance;
	double _alphaDistance;

}

@property (nonatomic,retain) UIView * overlayView;                               //@synthesize overlayView=_overlayView - In the implementation block
@property (nonatomic,retain) SXComponentView * headerComponentView;              //@synthesize headerComponentView=_headerComponentView - In the implementation block
@property (assign,nonatomic) double scrollDistance;                              //@synthesize scrollDistance=_scrollDistance - In the implementation block
@property (assign,nonatomic) double alphaDistance;                               //@synthesize alphaDistance=_alphaDistance - In the implementation block
-(void)prepareAnimation;
-(void)updateAnimationWithFactor:(double)arg1 ;
-(id)componentViewToAnimate;
-(BOOL)shouldFinishAtEndOfScrollView;
-(double)factorForVisibileBounds:(CGRect)arg1 andAbsoluteComponentRect:(CGRect)arg2 ;
-(void)setHeaderComponentView:(SXComponentView *)arg1 ;
-(SXComponentView *)headerComponentView;
-(void)setScrollDistance:(double)arg1 ;
-(void)setAlphaDistance:(double)arg1 ;
-(double)scrollDistance;
-(double)alphaDistance;
-(void)startAnimation;
-(void)finishAnimation;
-(void)setOverlayView:(UIView *)arg1 ;
-(UIView *)overlayView;
@end

