/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXComponentBehavior.h>

@interface SXParallaxComponentBehavior : SXComponentBehavior {

	int _cachedDirection;

}

@property (nonatomic,readonly) double factor; 
@property (nonatomic,readonly) int direction; 
@property (nonatomic,readonly) int cachedDirection;              //@synthesize cachedDirection=_cachedDirection - In the implementation block
+(id)typeString;
-(int)direction;
-(double)factor;
-(Class)handlerClassForComponent:(id)arg1 ;
-(int)cachedDirection;
-(int)directionWithValue:(id)arg1 withType:(int)arg2 ;
@end

