/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <iAd/ADPrerollView.h>
#import <libobjc.A.dylib/ADPrerollViewDelegate.h>

@class SXAdController, SXAVPlayer, SXPrerollAdResponse, NSString;

@interface SXPrerollView : ADPrerollView <ADPrerollViewDelegate> {

	int _state;
	SXAdController* _adController;
	SXAVPlayer* _player;
	/*^block*/id _stateChangedBlock;
	/*^block*/id _cancelHandler;
	SXPrerollAdResponse* _adResponse;

}

@property (nonatomic,__weak,readonly) SXAdController * adController;              //@synthesize adController=_adController - In the implementation block
@property (assign,nonatomic) int state;                                           //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) SXAVPlayer * player;                                 //@synthesize player=_player - In the implementation block
@property (nonatomic,copy) id stateChangedBlock;                                  //@synthesize stateChangedBlock=_stateChangedBlock - In the implementation block
@property (nonatomic,copy) id cancelHandler;                                      //@synthesize cancelHandler=_cancelHandler - In the implementation block
@property (nonatomic,retain) SXPrerollAdResponse * adResponse;                    //@synthesize adResponse=_adResponse - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(SXAdController *)adController;
-(void)setAdResponse:(SXPrerollAdResponse *)arg1 ;
-(void)loadPlayer;
-(SXPrerollAdResponse *)adResponse;
-(void)skipped;
-(void)actionPressed;
-(id)stateChangedBlock;
-(id)initWithAdController:(id)arg1 ;
-(void)setStateChangedBlock:(id)arg1 ;
-(void)setCancelHandler:(id)arg1 ;
-(void)dealloc;
-(int)state;
-(void)setState:(int)arg1 ;
-(void)stopLoading;
-(void)pause;
-(void)finish;
-(void)changeState:(int)arg1 ;
-(id)cancelHandler;
-(void)shutdown;
-(void)doneButtonPressed;
-(void)startLoading;
-(void)setPlayer:(SXAVPlayer *)arg1 ;
-(void)play;
-(SXAVPlayer *)player;
-(void)actionButtonPressed;
-(BOOL)prerollViewRequestsEmbeddedStatus;
-(void)playButtonPressed;
-(void)pauseButtonPressed;
-(void)skipButtonPressed;
@end

