/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface SXResolvedComponentLayout : NSObject {

	NSString* _componentIdentifier;
	NSArray* _dependencies;
	long long _dependencyAttribute;

}

@property (nonatomic,retain) NSString * componentIdentifier;              //@synthesize componentIdentifier=_componentIdentifier - In the implementation block
@property (nonatomic,retain) NSArray * dependencies;                      //@synthesize dependencies=_dependencies - In the implementation block
@property (assign,nonatomic) long long dependencyAttribute;               //@synthesize dependencyAttribute=_dependencyAttribute - In the implementation block
-(void)setComponentIdentifier:(NSString *)arg1 ;
-(NSString *)componentIdentifier;
-(void)setDependencyAttribute:(long long)arg1 ;
-(long long)dependencyAttribute;
-(NSArray *)dependencies;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(void)setDependencies:(NSArray *)arg1 ;
@end

