/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXComponentAnimationHandler.h>

@interface SXScaleAndFadeComponentAnimationHandler : SXComponentAnimationHandler
-(void)prepareAnimation;
-(double)initialAlpha;
-(void)updateAnimationWithFactor:(double)arg1 ;
-(void)animationDidStop:(id)arg1 finished:(BOOL)arg2 ;
-(void)startAnimation;
-(double)initialScale;
-(void)finishAnimation;
@end

