/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXComponentBlueprint.h>

@interface SXStripGalleryComponentBlueprint : SXComponentBlueprint {

	double _contentWidth;
	double _contentOffset;

}

@property (assign,nonatomic) double contentWidth;               //@synthesize contentWidth=_contentWidth - In the implementation block
@property (assign,nonatomic) double contentOffset;              //@synthesize contentOffset=_contentOffset - In the implementation block
-(double)contentOffset;
-(void)setContentOffset:(double)arg1 ;
-(double)contentWidth;
-(void)setContentWidth:(double)arg1 ;
@end

