/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <TSReading/TSDWrappable.h>

@class SXTextExclusionPath, TSDWrapPolygon, NSString;

@interface SXTextExclusionPathWrapper : NSObject <TSDWrappable> {

	BOOL _isRectangular;
	SXTextExclusionPath* _exclusionPath;
	TSDWrapPolygon* _myWrapPolygon;

}

@property (nonatomic,__weak,readonly) SXTextExclusionPath * exclusionPath;              //@synthesize exclusionPath=_exclusionPath - In the implementation block
@property (nonatomic,readonly) BOOL isRectangular;                                      //@synthesize isRectangular=_isRectangular - In the implementation block
@property (nonatomic,readonly) TSDWrapPolygon * myWrapPolygon;                          //@synthesize myWrapPolygon=_myWrapPolygon - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) BOOL hasAlpha; 
-(SXTextExclusionPath *)exclusionPath;
-(CGRect)boundsInRoot;
-(int)wrapDirection;
-(int)wrapFitType;
-(TSDWrapPolygon *)myWrapPolygon;
-(id)initWithTextExclusionPath:(id)arg1 ;
-(BOOL)isHTMLWrap;
-(CGRect)boundsInfluencingExteriorWrap;
-(id)wrapPolygon;
-(BOOL)hasAlpha;
-(id)parent;
-(BOOL)isRectangular;
-(int)wrapType;
@end

