/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TSReading/TSWPRep.h>
#import <Silex/SXAXCustomRotorElement.h>

@class NSString;

@interface SXTextTangierTextRep : TSWPRep <SXAXCustomRotorElement>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)customRotorMembership;
-(BOOL)directlyManagesLayerContent;
-(void)didUpdateLayer:(id)arg1 ;
-(BOOL)shouldBeginEditingWithGesture:(id)arg1 ;
-(Class)wpEditorClass;
-(id)storage;
-(void)dealloc;
@end

