/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SXTextTangierInteractiveCanvasControllerDelegate <TSWPInteractiveCanvasControllerDelegate>
@optional
-(void)interactiveCanvasController:(id)arg1 willTriggerAction:(id)arg2 touchPoint:(CGPoint)arg3 touchAndHold:(BOOL)arg4;
-(void)interactiveCanvasController:(id)arg1 didTriggerAction:(id)arg2 info:(id)arg3 range:(NSRange)arg4 touchPoint:(CGPoint)arg5 touchAndHold:(BOOL)arg6;
-(void)interactiveCanvasController:(id)arg1 scrollViewWillBeginDragging:(id)arg2;
-(void)interactiveCanvasController:(id)arg1 scrollViewWillEndDragging:(id)arg2 withVelocity:(CGPoint)arg3 targetContentOffset:(inout CGPoint*)arg4;

@end

