/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TSWPLayoutTarget;
#import <Silex/Silex-Structs.h>
@class TSWPColumn, TSDLayout, TSDWrapPolygon, TSUPointerKeyDictionary;

@interface SXTextTangierTextWrapContext : NSObject {

	TSWPColumn* _column;
	TSDLayout*<TSWPLayoutTarget> _target;
	TSDWrapPolygon* _interiorWrapPolygon;
	TSUPointerKeyDictionary* _wrapPathInverseTransformInRootDictionary;
	CGAffineTransform _targetInverseTransformInRoot;

}

@property (nonatomic,readonly) TSWPColumn * column;                                                           //@synthesize column=_column - In the implementation block
@property (nonatomic,__weak,readonly) TSDLayout*<TSWPLayoutTarget> target;                                    //@synthesize target=_target - In the implementation block
@property (nonatomic,readonly) TSDWrapPolygon * interiorWrapPolygon;                                          //@synthesize interiorWrapPolygon=_interiorWrapPolygon - In the implementation block
@property (nonatomic,readonly) CGAffineTransform targetInverseTransformInRoot;                                //@synthesize targetInverseTransformInRoot=_targetInverseTransformInRoot - In the implementation block
@property (nonatomic,retain) TSUPointerKeyDictionary * wrapPathInverseTransformInRootDictionary;              //@synthesize wrapPathInverseTransformInRootDictionary=_wrapPathInverseTransformInRootDictionary - In the implementation block
-(id)initWithColumn:(id)arg1 targetLayout:(id)arg2 ;
-(CGAffineTransform)targetInverseTransformInRoot;
-(id)transformedWrapPolygonForWrappable:(id)arg1 canvasSpaceToWrapSpaceTransform:(CGAffineTransform)arg2 ;
-(TSUPointerKeyDictionary *)wrapPathInverseTransformInRootDictionary;
-(void)setWrapPathInverseTransformInRootDictionary:(TSUPointerKeyDictionary *)arg1 ;
-(TSDWrapPolygon *)interiorWrapPolygon;
-(void)setTarget:(TSDLayout*<TSWPLayoutTarget>)arg1 ;
-(TSDLayout*<TSWPLayoutTarget>)target;
-(TSWPColumn *)column;
@end

