/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TSReading/TSWPiOSCanvasViewController.h>

@class NSArray;

@interface SXTextTangierCanvasViewController : TSWPiOSCanvasViewController {

	NSArray* _installedGestureRecognizers;

}

@property (nonatomic,readonly) NSArray * installedGestureRecognizers;              //@synthesize installedGestureRecognizers=_installedGestureRecognizers - In the implementation block
-(NSArray *)installedGestureRecognizers;
-(void)setUpGestureRecognizers;
-(id)backgroundColorForMagnifier;
-(id)actionForHyperlink:(id)arg1 inRep:(id)arg2 gesture:(id)arg3 ;
-(id)targetForAction:(SEL)arg1 withSender:(id)arg2 ;
@end

