/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <TSReading/TSDDrawableInfo.h>

@class SXTextExclusionPath;

@interface SXTextTangierAttachmentInfo : TSDDrawableInfo {

	SXTextExclusionPath* _exclusionPath;
	NSRange _actualRange;

}

@property (nonatomic,retain) SXTextExclusionPath * exclusionPath;              //@synthesize exclusionPath=_exclusionPath - In the implementation block
@property (assign,nonatomic) NSRange actualRange;                              //@synthesize actualRange=_actualRange - In the implementation block
-(NSRange)actualRange;
-(SXTextExclusionPath *)exclusionPath;
-(void)setExclusionPath:(SXTextExclusionPath *)arg1 ;
-(void)setActualRange:(NSRange)arg1 ;
-(Class)repClass;
-(Class)layoutClass;
@end

