/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXJSONObject.h>

@class UIColor;

@interface SXTextDecoration : SXJSONObject

@property (nonatomic,readonly) UIColor * color; 
@property (nonatomic,readonly) long long width; 
@property (nonatomic,readonly) int style; 
-(int)style;
-(long long)width;
-(UIColor *)color;
-(int)styleWithValue:(id)arg1 withType:(int)arg2 ;
@end

