/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:07 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <TSReading/TSDContainerInfo.h>
#import <Silex/SXTangierRepDirectLayerHostingInfo.h>

@protocol TSDRepDirectLayerHosting;
@class SXTextTangierStorage, NSSet, NSString;

@interface SXTextTangierContainerInfo : TSDContainerInfo <SXTangierRepDirectLayerHostingInfo> {

	BOOL _isSelectable;
	BOOL _shouldHyphenate;
	SXTextTangierStorage* _storage;
	NSSet* _fixedExclusionPaths;
	id<TSDRepDirectLayerHosting> _directLayerHost;

}

@property (nonatomic,readonly) SXTextTangierStorage * storage;                                 //@synthesize storage=_storage - In the implementation block
@property (nonatomic,retain) NSSet * fixedExclusionPaths;                                      //@synthesize fixedExclusionPaths=_fixedExclusionPaths - In the implementation block
@property (nonatomic,retain) NSSet * rangedExclusionPaths; 
@property (assign,nonatomic) BOOL isSelectable;                                                //@synthesize isSelectable=_isSelectable - In the implementation block
@property (assign,nonatomic) BOOL shouldHyphenate;                                             //@synthesize shouldHyphenate=_shouldHyphenate - In the implementation block
@property (assign,nonatomic,__weak) id<TSDRepDirectLayerHosting> directLayerHost;              //@synthesize directLayerHost=_directLayerHost - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id<TSDRepDirectLayerHosting>)directLayerHost;
-(void)setDirectLayerHost:(id<TSDRepDirectLayerHosting>)arg1 ;
-(void)setShouldHyphenate:(BOOL)arg1 ;
-(NSSet *)rangedExclusionPaths;
-(void)setRangedExclusionPaths:(NSSet *)arg1 ;
-(id)initWithContext:(id)arg1 geometry:(id)arg2 stylesheet:(id)arg3 textSource:(id)arg4 ;
-(NSSet *)fixedExclusionPaths;
-(void)setFixedExclusionPaths:(NSSet *)arg1 ;
-(Class)repClass;
-(BOOL)shouldHyphenate;
-(SXTextTangierStorage *)storage;
-(BOOL)isSelectable;
-(void)setIsSelectable:(BOOL)arg1 ;
-(Class)layoutClass;
@end

