/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/SXOEmbedComponentView.h>

@interface SXTwitterOEmbedComponentView : SXOEmbedComponentView
-(id)additionalQueryParameters;
-(id)modifiedHTML:(id)arg1 ;
-(BOOL)shouldAllowRequestToURL:(id)arg1 ;
-(void)updateWebView:(id)arg1 toWidth:(double)arg2 ;
-(id)unableToLoadMessage;
-(id)URL;
@end

