/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SXUnitConverter : NSObject
+(double)convertValueToPoints:(id)arg1 contextBlock:(/*^block*/id)arg2 ;
+(double)convertViewportHeightToPoints:(double)arg1 contextBlock:(/*^block*/id)arg2 ;
+(double)convertViewportWidthToPoints:(double)arg1 contextBlock:(/*^block*/id)arg2 ;
+(double)convertViewportMinToPoints:(double)arg1 contextBlock:(/*^block*/id)arg2 ;
+(double)convertViewportMaxToPoints:(double)arg1 contextBlock:(/*^block*/id)arg2 ;
+(double)convertColumnGutterToPoints:(double)arg1 contextBlock:(/*^block*/id)arg2 ;
+(double)convertComponentWidthToPoints:(double)arg1 contextBlock:(/*^block*/id)arg2 ;
@end

