/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:06 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIView.h>

@protocol SXVideoOverlayButton;
@class UIView, UIActivityIndicatorView, UIImageView, UIImage;

@interface SXVideoPlayerPosterFrameView : UIView {

	UIView*<SXVideoOverlayButton> _playButton;
	UIActivityIndicatorView* _activityIndicator;
	UIImageView* _imageView;
	CGRect _crop;

}

@property (nonatomic,readonly) UIView*<SXVideoOverlayButton> playButton;                 //@synthesize playButton=_playButton - In the implementation block
@property (nonatomic,retain) UIImage * image; 
@property (assign,nonatomic) CGRect crop;                                                //@synthesize crop=_crop - In the implementation block
@property (nonatomic,readonly) UIActivityIndicatorView * activityIndicator;              //@synthesize activityIndicator=_activityIndicator - In the implementation block
@property (nonatomic,readonly) UIImageView * imageView;                                  //@synthesize imageView=_imageView - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setImage:(UIImage *)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(UIImage *)image;
-(UIImageView *)imageView;
-(UIActivityIndicatorView *)activityIndicator;
-(void)startActivityIndicator;
-(void)stopActivityIndicator;
-(UIView*<SXVideoOverlayButton>)playButton;
-(CGRect)crop;
-(void)setCrop:(CGRect)arg1 ;
@end

