/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMapTable, NSMutableDictionary;

@interface SXVideoController : NSObject {

	NSMapTable* _videoPlayerViewControllers;
	NSMutableDictionary* _receiveOwnershipBlocks;
	NSMutableDictionary* _resignOwnershipBlocks;

}

@property (nonatomic,readonly) NSMapTable * videoPlayerViewControllers;                   //@synthesize videoPlayerViewControllers=_videoPlayerViewControllers - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * receiveOwnershipBlocks;              //@synthesize receiveOwnershipBlocks=_receiveOwnershipBlocks - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * resignOwnershipBlocks;               //@synthesize resignOwnershipBlocks=_resignOwnershipBlocks - In the implementation block
-(id)videoPlayerViewControllerForURL:(id)arg1 existing:(inout BOOL*)arg2 receiveOwnershipBlock:(/*^block*/id)arg3 ;
-(NSMapTable *)videoPlayerViewControllers;
-(NSMutableDictionary *)resignOwnershipBlocks;
-(NSMutableDictionary *)receiveOwnershipBlocks;
-(/*^block*/id)registerExistingVideoPlayerViewController:(id)arg1 ;
-(id)init;
@end

