/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:08 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/News.app/Frameworks/Silex.framework/Silex
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Silex/Silex-Structs.h>
#import <UIKit/UIViewController.h>
#import <Silex/SXPlayerViewControllerHost.h>

@protocol SXVideoPlayerDelegate, SXVideoPlayerDataSource;
@class NSString, NSURL, SXContext, SXVideoPlayerPosterFrameView, SXPrerollView, AVPlayerViewController, SXAVPlayer, SXTouchAbsorbingView;

@interface SXVideoPlayerViewController : UIViewController <SXPlayerViewControllerHost> {

	BOOL _showPlaybackControls;
	BOOL _startVideoPlaybackWhenReady;
	BOOL _startPrerollPlaybackWhenReady;
	BOOL _reusedPlayerViewController;
	int _state;
	int _mode;
	int _desiredAction;
	NSString* _resourceIdentifier;
	NSURL* _videoURL;
	id<SXVideoPlayerDelegate> _delegate;
	id<SXVideoPlayerDataSource> _dataSource;
	SXContext* _context;
	SXVideoPlayerPosterFrameView* _posterFrameView;
	/*^block*/id _contextCancelHandler;
	/*^block*/id _thumbnailCancelHandler;
	SXPrerollView* _prerollView;
	AVPlayerViewController* _playerViewController;
	SXAVPlayer* _videoPlayer;
	SXTouchAbsorbingView* _touchAbsorbingView;

}

@property (nonatomic,readonly) NSURL * videoURL;                                            //@synthesize videoURL=_videoURL - In the implementation block
@property (assign,nonatomic,__weak) id<SXVideoPlayerDelegate> delegate;                     //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<SXVideoPlayerDataSource> dataSource;                 //@synthesize dataSource=_dataSource - In the implementation block
@property (getter=isFullScreen,nonatomic,readonly) BOOL fullScreen; 
@property (assign,nonatomic) BOOL showPlaybackControls;                                     //@synthesize showPlaybackControls=_showPlaybackControls - In the implementation block
@property (assign,nonatomic) int state;                                                     //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) int mode;                                                      //@synthesize mode=_mode - In the implementation block
@property (nonatomic,readonly) BOOL playerViewControllerLoaded; 
@property (assign,nonatomic) int desiredAction;                                             //@synthesize desiredAction=_desiredAction - In the implementation block
@property (nonatomic,retain) SXContext * context;                                           //@synthesize context=_context - In the implementation block
@property (nonatomic,readonly) SXVideoPlayerPosterFrameView * posterFrameView;              //@synthesize posterFrameView=_posterFrameView - In the implementation block
@property (nonatomic,copy) id contextCancelHandler;                                         //@synthesize contextCancelHandler=_contextCancelHandler - In the implementation block
@property (nonatomic,copy) id thumbnailCancelHandler;                                       //@synthesize thumbnailCancelHandler=_thumbnailCancelHandler - In the implementation block
@property (nonatomic,retain) SXPrerollView * prerollView;                                   //@synthesize prerollView=_prerollView - In the implementation block
@property (nonatomic,retain) AVPlayerViewController * playerViewController;                 //@synthesize playerViewController=_playerViewController - In the implementation block
@property (nonatomic,retain) SXAVPlayer * videoPlayer;                                      //@synthesize videoPlayer=_videoPlayer - In the implementation block
@property (nonatomic,readonly) NSString * resourceIdentifier;                               //@synthesize resourceIdentifier=_resourceIdentifier - In the implementation block
@property (assign,nonatomic) BOOL startVideoPlaybackWhenReady;                              //@synthesize startVideoPlaybackWhenReady=_startVideoPlaybackWhenReady - In the implementation block
@property (assign,nonatomic) BOOL startPrerollPlaybackWhenReady;                            //@synthesize startPrerollPlaybackWhenReady=_startPrerollPlaybackWhenReady - In the implementation block
@property (nonatomic,retain) SXTouchAbsorbingView * touchAbsorbingView;                     //@synthesize touchAbsorbingView=_touchAbsorbingView - In the implementation block
@property (assign,nonatomic) BOOL reusedPlayerViewController;                               //@synthesize reusedPlayerViewController=_reusedPlayerViewController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSString *)resourceIdentifier;
-(void)playButtonTapped:(id)arg1 ;
-(BOOL)showPlaybackControls;
-(void)setShowPlaybackControls:(BOOL)arg1 ;
-(BOOL)playerViewControllerLoaded;
-(void)exitFullScreenWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)destroyPrerollView;
-(void)destroyVideoPlayer;
-(SXTouchAbsorbingView *)touchAbsorbingView;
-(int)desiredAction;
-(BOOL)supportsPreroll;
-(void)setDesiredAction:(int)arg1 ;
-(void)setStartVideoPlaybackWhenReady:(BOOL)arg1 ;
-(SXPrerollView *)prerollView;
-(void)setStartPrerollPlaybackWhenReady:(BOOL)arg1 ;
-(void)cancelContextRequest;
-(void)transitionFrom:(id)arg1 toView:(id)arg2 completionBlock:(/*^block*/id)arg3 ;
-(BOOL)shouldLoadPreroll;
-(void)loadPreroll;
-(BOOL)shouldLoadVideo;
-(void)createVideoPlayer;
-(void)loadVideo;
-(void)setContextCancelHandler:(id)arg1 ;
-(id)contextCancelHandler;
-(void)setThumbnailCancelHandler:(id)arg1 ;
-(id)thumbnailCancelHandler;
-(BOOL)shouldPlayVideo;
-(BOOL)shouldDisplayVideo;
-(void)showVideoPlayer;
-(BOOL)shouldStartVideoPlaybackWhenReady;
-(void)playVideo;
-(void)videoPlaybackWillResume;
-(void)videoPlaybackWillStart;
-(void)videoPlaybackResumed;
-(void)videoPlaybackStarted;
-(void)videoPlaybackPaused;
-(void)videoPlaybackFinished;
-(void)videoPlaybackFailed;
-(void)setReusedPlayerViewController:(BOOL)arg1 ;
-(BOOL)reusedPlayerViewController;
-(BOOL)shouldPlayPreroll;
-(void)showPrerollView;
-(BOOL)shouldStartPrerollPlaybackWhenReady;
-(void)playPreroll;
-(void)prerollPlaybackWillStart;
-(void)prerollPlaybackWillResume;
-(void)prerollPlaybackStarted;
-(void)prerollPlaybackResumed;
-(void)prerollPlaybackPaused;
-(void)prerollPlaybackFinished;
-(void)prerollPlaybackFailed;
-(void)setPrerollView:(SXPrerollView *)arg1 ;
-(BOOL)startVideoPlaybackWhenReady;
-(BOOL)startPrerollPlaybackWhenReady;
-(id)resourceIdentifierForVideoURL:(id)arg1 ;
-(void)playerViewControllerWillDetatch:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)initWithVideoURL:(id)arg1 delegate:(id)arg2 dataSource:(id)arg3 ;
-(void)enterFullScreenWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)setTouchAbsorbingView:(SXTouchAbsorbingView *)arg1 ;
-(void)setDataSource:(id<SXVideoPlayerDataSource>)arg1 ;
-(void)setDelegate:(id<SXVideoPlayerDelegate>)arg1 ;
-(void)dealloc;
-(void)setFrame:(CGRect)arg1 ;
-(id<SXVideoPlayerDataSource>)dataSource;
-(id<SXVideoPlayerDelegate>)delegate;
-(int)state;
-(void)setState:(int)arg1 ;
-(void)reset;
-(SXContext *)context;
-(void)didMoveToParentViewController:(id)arg1 ;
-(void)viewDidLoad;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(void)resume;
-(void)setContext:(SXContext *)arg1 ;
-(void)pause;
-(void)requestThumbnail;
-(void)cancelThumbnailRequest;
-(void)setPlayerViewController:(AVPlayerViewController *)arg1 ;
-(AVPlayerViewController *)playerViewController;
-(SXAVPlayer *)videoPlayer;
-(NSURL *)videoURL;
-(void)play;
-(void)setVideoPlayer:(SXAVPlayer *)arg1 ;
-(SXVideoPlayerPosterFrameView *)posterFrameView;
-(void)requestContext;
-(void)seekToStart;
-(BOOL)isFullScreen;
@end

