/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:04 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileSafari.app/Safari.wkbundle/Safari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WebUI/WBUWebProcessPlugIn.h>

@interface SafariWebProcessPlugIn : WBUWebProcessPlugIn
-(id)pageControllerWithBrowserContextController:(id)arg1 ;
@end

