/*
* This header is generated by classdump-dyld 1.0
* on Saturday, July 30, 2016 at 2:25:04 AM Japan Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /Applications/MobileSafari.app/Safari.wkbundle/Safari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariServices/_SFWebProcessPlugInReaderEnabledPageController.h>
#import <Safari/PageLoadTestWebProcessController.h>

@protocol AppBannerMetaTagContentObserver;
@class _WKRemoteObjectInterface, MeasurementControllerBase, NSString;

@interface WebProcessPlugInBrowserPageController : _SFWebProcessPlugInReaderEnabledPageController <PageLoadTestWebProcessController> {

	_WKRemoteObjectInterface* _pageLoadTestControllerInterface;
	MeasurementControllerBase* _pageLoadTestMeasurementController;
	id<AppBannerMetaTagContentObserver> _appBannerObserverProxy;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_setupPageLoadTestController;
-(void)_logPageLoadStarted:(id)arg1 ;
-(void)_logPageLoadCompleted:(id)arg1 ;
-(id)_appBannerMetaTagObserverProxy;
-(id)_appBannerMetaElementInHeaderElement:(id)arg1 ;
-(id)_searchForSmartAppBannerMetaContent;
-(void)enablePageMemoryMeasurementCollection;
-(void)enablePageLoadMeasurementCollection;
-(void)dealloc;
-(id)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 willSendRequestForResource:(unsigned long long)arg3 request:(id)arg4 redirectResponse:(id)arg5 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFinishDocumentLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didHandleOnloadEventsForFrame:(id)arg2 ;
-(id)initWithPlugIn:(id)arg1 contextController:(id)arg2 ;
-(void)willDestroyBrowserContextController:(id)arg1 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didStartProvisionalLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didCommitLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFailProvisionalLoadWithErrorForFrame:(id)arg2 error:(id)arg3 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFailLoadWithErrorForFrame:(id)arg2 error:(id)arg3 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFinishLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 globalObjectIsAvailableForFrame:(id)arg2 inScriptWorld:(id)arg3 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didRemoveFrameFromHierarchy:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFirstVisuallyNonEmptyLayoutForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didInitiateLoadForResource:(unsigned long long)arg3 request:(id)arg4 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didFinishLoadForResource:(unsigned long long)arg3 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didFailLoadForResource:(unsigned long long)arg3 error:(id)arg4 ;
-(id)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 userAgentForURL:(id)arg3 ;
-(void)_powerlog:(id)arg1 ;
@end

